main:
  - name: Organización
    identifier: schedule
    url: /schedule/
    weight: 1
  - name: Planificación
    parent: schedule
    url: /schedule/
    weight: 1
  - name: Syllabus
    parent: schedule
    url: /syllabus/
    weight: 2
  - name: Clases
    url: /content/
    weight: 3
  - name: Prácticos
    url: /example/
    weight: 4
  - name: Evaluaciones <i class="fab fa-github"></i>
    identifier: assignment
    url: /assignment/
    weight: 5
  - name: Controles
    parent: assignment
    url: /assignment/
    weight: 6
  - name: 'Github Classroom<i class="fab fa-github"></i>'
    parent: assignment
    url: "https://classroom.github.com/classrooms/86887318-learn-r-uah-2021"
    weight: 7
  - name: Recursos
    url: /resource/
    weight: 8
  - name: '<i class="fab fa-slack"></i>'
    url: "https://join.slack.com/t/estadisticaii-uah/shared_invite/zt-1qi7am4o2-7pVVgPC~s0IcBKwqSRWSvQ"
    weight: 9
  - name: '<i class="fab fa-r-project"></i>'
    url: https://rstudio.cloud/
    weight: 10

content:
  - name: Información general
    weight: 1
  - name: Contenido
    weight: 2
example:
  - name: Información general
    weight: 1
  - name: Datos
    weight: 2
  - name: Ejemplos
    weight: 3
assignment:
  - name: Información general
    weight: 1
  - name: Controles
    weight: 2
  - name: Prueba
    weight: 2
  - name: Proyecto 
    weight: 3
resource:
  - name: Recursos
    weight: 1
  - name: Material complementario
    weight: 3
  - name: Tutoriales
    weight: 2
