---
title: "Pauta proyecto de investigación"
linktitle: "14: Pauta proyecto de investigación"
date: "2021-05-30"
menu:
  example:
    parent: Ejemplos
    weight: 14
type: docs
toc: true
editor_options: 
  chunk_output_type: console
---

# Pauta proyecto de investigación, examen del curso

El objetivo central del proyecto de investigación es analizar un fenómeno que consideran de interés y que puede ser trabajado desde la información disponible en bases de datos. El centro de su trabajo, no obstante, es el análisis de datos mediante modelos de regresión lineal utilizando los *softwares R* y *RStudio*.

Se deben construir al menos dos regresiones lineales múltiples y compararlas entre sí. El foco debe estar en considerar el ajuste de ambos modelos y sus errores de especificación. Por ejemplo, incluir en un modelo variables irrelevantes u omitir variables relevantes. A partir de aquello, realizar test de significancia estadística para cada coeficiente y de manera global.

La aplicación de transformaciones funcionales (logarítmica, cuadrática o efectos de interacción) y el chequeo de los supuestos de regresión no son obligatorios, pero de realizarse, tendrán una bonificación de puntaje.

A partir de su análisis, deben redactar un informe que contenga los siguientes apartados:

## 1. Título

El título debe ser breve y referir a la temática escogida.

## 2. Introducción (800-1000 palabras)

Definir la temática escogida, explicar por qué es relevante su estudio y presentar sus conceptos principales, además de definirlos. Estos deben ahondar el objeto de estudio (su origen, definición e investigaciones principales) además de los posibles factores que explican al objeto. Se debe considerar al menos 1 referencia bibliográfica por cada uno de los factores.

## 3. Objetivo general e hipótesis (300 palabras)

### 3.1. Objetivo general (50 palabras)

Esclarecer la relación entre los conceptos, distinguiendo entre variable dependiente y variables independientes. El objetivo general se formula utilizando un verbo en infinitivo, identifica en su formulación un objeto de estudio, sujetos de estudio y el espacio y tiempo del fenómeno estudiado.

### 3.2. Hipótesis (250 palabras)

Elaborar una hipótesis por cada variable independiente relacionándola con la variable dependiente. Considerar el sentido y magnitud de la relación.

## 6. Metodología (400 palabras)

### 6.1. Datos

Identificar la población de estudio, la muestra utilizada y el número de casos. Se debe explicitar el(los) tema(s) del que trata la encuesta seleccionada, así como la institución u organismo que produjo los datos. Además, el objetivo general de la encuesta seleccionada y el año de publicación o levantamiento de los datos.

### 6.2. Variables

Identificar la selección de variables dependiente (cuantitativa) e independientes (cuantitativas o categóricas, mínimo 3).

### 6.3. Métodos utilizados

Describir brevemente el método de regresión utilizado.

## 7. Análisis (máximo 1500 palabras)

### 7.1. Análisis descriptivos

Exponer e interpretar brevemente las principales medidas de tendencia central (media, moda o mediana) de cada una de las variables seleccionadas.

### 7.2. Modelos de regresión

Presentar los modelos de regresión realizados mediante una tabla en formato APA (la que trabajamos en los prácticos).

Para cada modelo, interpretar sus coeficientes en cuanto a su magnitud como también de significancia estadística y ajuste global del modelo ($R^2$). Se debe hacer referencia a cada hipótesis al momento de analizar los coeficientes, además de indicar cuál modelo presenta mayor bondad de ajuste.

## 8. Conclusiones (350 palabras)

Resumir sus resultados principales enfatizando en la relación entre variable dependiente y variables independientes. Señalar limitaciones del estudio y proponer investigaciones sobre la temática hacia el futuro.

## 9. Referencias

Listado de bibliografía utilizada en formato APA.

## 10. Formato

-   Archivo .pdf en tamaño carta
-   Fuente *Times New Roman*, tamaño 12, interlineado 1,5 y márgenes normales (2,5 cm \* superior e inferior, 3 cm derecho e izquierdo)
-   Incluir páginas de portada e índice
