<!DOCTYPE html>
<html lang="en-us" 
      xmlns:og="http://ogp.me/ns#" 
      xmlns:fb="https://www.facebook.com/2008/fbml">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  
  
  
    <meta name="generator" content="Wowchemy 5.2.0 for Hugo" />
  

  

  
  
  
  
  
  

  

  
  
  
    
  
  <meta name="description" content="0. Objetivo del prácticoEl presente práctico tiene dos objetivos:
Comprender las implicancias de la incorporación de más de un predictor en modelos de regresión lineal.
Aprender a estimar una regresión lineal múltiple en R con lm()." />

  
  <link rel="alternate" hreflang="en-us" href="/example/06-practico/" />

  







  




  
  
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  

  
  
  
    <meta name="theme-color" content="#1a9875" />
  

  
  
    
    <script src="/js/mathjax-config.js"></script>
  

  
  
  
  
    
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha256-FMvZuGapsJLjouA6k7Eo2lusoAX9i0ShlWFG6qt7SLc=" crossorigin="anonymous">

    
    

    
    
    
      
    
    

    
    
    

    

    
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" integrity="" crossorigin="anonymous" async></script>
      
    
      
      

      
      

      
    
      
      

      
      

      
    
  

  
  
  
    
      
      
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Fira+Sans+Condensed:400,400i,700,700i%7CBarlow:ital,wght@0,400;0,700;1,400;1,700&display=swap">
      
    
  

  
  
  
  
  
  <link rel="stylesheet" href="/css/wowchemy.6c40d5e91ad0908cd1753452468e8c67.css" />

  



  

  

  




  
  
  

  

  
    <link rel="manifest" href="/index.webmanifest" />
  

  <link rel="icon" type="image/png" href="/media/icon_hua2ec155b4296a9c9791d015323e16eb5_11927_32x32_fill_lanczos_center_2.png" />
  <link rel="apple-touch-icon" type="image/png" href="/media/icon_hua2ec155b4296a9c9791d015323e16eb5_11927_180x180_fill_lanczos_center_2.png" />

  <link rel="canonical" href="/example/06-practico/" />

  
  
  
  
  
  
  
  
    
    
  
  
  <meta property="twitter:card" content="summary" />
  
    <meta property="twitter:site" content="@valentiandrade" />
    <meta property="twitter:creator" content="@valentiandrade" />
  
  <meta property="og:site_name" content="Estadística II" />
  <meta property="og:url" content="/example/06-practico/" />
  <meta property="og:title" content="Regresión lineal múltiple | Estadística II" />
  <meta property="og:description" content="0. Objetivo del prácticoEl presente práctico tiene dos objetivos:
Comprender las implicancias de la incorporación de más de un predictor en modelos de regresión lineal.
Aprender a estimar una regresión lineal múltiple en R con lm()." /><meta property="og:image" content="/media/logo_huec1c53a9c99ba801c510916ffbd8bc18_109138_300x300_fit_lanczos_2.png" />
    <meta property="twitter:image" content="/media/logo_huec1c53a9c99ba801c510916ffbd8bc18_109138_300x300_fit_lanczos_2.png" /><meta property="og:locale" content="en-us" />
  
    
    
  

  



  

  

  <link rel="stylesheet" type="text/css" href="/custom-css/print.css" media="print" />

  <link rel="shortcut icon" href="/favicon.ico" />
  <link rel="apple-touch-icon-precomposed" sizes="57x57" href="/img/apple-touch-icon-57x57.png" />
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/img/apple-touch-icon-114x114.png" />
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/img/apple-touch-icon-72x72.png" />
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/img/apple-touch-icon-144x144.png" />
  <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/img/apple-touch-icon-120x120.png" />
  <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/img/apple-touch-icon-152x152.png" />
  <link rel="icon" type="image/png" href="/img/favicon-32x32.png" sizes="32x32" />
  <link rel="icon" type="image/png" href="/img/favicon-16x16.png" sizes="16x16" />
  <meta name="application-name" content=": Estadística II" />
  <meta name="msapplication-TileColor" content="#FFFFFF" />
  <meta name="msapplication-TileImage" content="/img/mstile-144x144.png" />


  <title>Regresión lineal múltiple | Estadística II</title>
</head>


<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" class="page-wrapper  ">

  
  
  
  
  
  <script src="/js/wowchemy-init.js"></script>

    




    











  


<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container-xl">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/"><img src="/media/logo_huec1c53a9c99ba801c510916ffbd8bc18_109138_0x70_resize_lanczos_2.png" alt="Estadística II"></a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar-content" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/"><img src="/media/logo_huec1c53a9c99ba801c510916ffbd8bc18_109138_0x70_resize_lanczos_2.png" alt="Estadística II"></a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-end" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"><span>Organización</span><span class="caret"></span>
          </a>
          <div class="dropdown-menu">
            
              <a class="dropdown-item" href="/schedule/"><span>Planificación</span></a>
            
              <a class="dropdown-item" href="/syllabus/"><span>Syllabus</span></a>
            
          </div>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/content/"><span>Clases</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link  active" href="/example/"><span>Prácticos</span></a>
        </li>

        
        

        
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"><span>Evaluaciones <i class="fab fa-github"></i></span><span class="caret"></span>
          </a>
          <div class="dropdown-menu">
            
              <a class="dropdown-item" href="/assignment/"><span>Controles</span></a>
            
              <a class="dropdown-item" href="https://classroom.github.com/classrooms/86887318-learn-r-uah-2021"><span>Github Classroom<i class="fab fa-github"></i></span></a>
            
          </div>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/resource/"><span>Recursos</span></a>
        </li>

        
        

        

        
        
        
          
            
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="https://join.slack.com/t/estadisticaii-uah/shared_invite/zt-1qi7am4o2-7pVVgPC~s0IcBKwqSRWSvQ" target="_blank" rel="noopener"><span><i class="fab fa-slack"></i></span></a>
        </li>

        
        

        

        
        
        
          
            
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="https://rstudio.cloud/" target="_blank" rel="noopener"><span><i class="fab fa-r-project"></i></span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">

      
      

      
      

      
      

      
      

    </ul>

  </div>
</nav>



    

<div class="container-fluid docs">
    <div class="row flex-xl-nowrap">
        <div class="col-12 col-md-3 col-xl-2 docs-sidebar">
            





  
    
  




<form class="docs-search d-flex align-items-center">
  <button class="btn docs-toggle d-md-none p-0 mr-3" type="button" data-toggle="collapse" data-target="#docs-nav" aria-controls="docs-nav" aria-expanded="false" aria-label="Toggle section navigation">
    <span><i class="fas fa-bars"></i></span>
  </button>

  
</form>

<nav class="collapse docs-links" id="docs-nav">
  

  
  
  
    
  

  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/example/">Información general</a>
    <ul class="nav docs-sidenav">
      
      <li >
        <a href="/example/">Prácticos (códigos de ejemplo)</a>
      </li>

      
    </ul>
    

  </div>
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" >Datos</a>

  </div>
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/example/01-practico/">Ejemplos</a>
    <ul class="nav docs-sidenav">
      
      <li >
        <a href="/example/01-practico/">1: Variables aleatorias y distribuciones</a>
      </li>

      
      <li >
        <a href="/example/02-practico/">2: Inferencia</a>
      </li>

      
      <li >
        <a href="/example/032-practico/">3: RMarkdown</a>
      </li>

      
      <li >
        <a href="/example/03-practico/">3: R, RStudio y Github</a>
      </li>

      
      <li >
        <a href="/example/05-practico/">5: Regresión lineal simple con diseño muestral y bondad de ajuste</a>
      </li>

      
      <li class="active">
        <a href="/example/06-practico/">6: Regresión lineal múltiple</a>
      </li>

      
      <li >
        <a href="/example/07-practico/">7: Regresión lineal múltiple y predictores categóricos</a>
      </li>

      
      <li >
        <a href="/example/08-practico/">8: Inferencia y predicción</a>
      </li>

      
      <li >
        <a href="/example/09-practico/">9: Transformaciones funcionales</a>
      </li>

      
      <li >
        <a href="/example/10-practico/">10: Relaciones no lineales y términos de interacción</a>
      </li>

      
      <li >
        <a href="/example/11-practico/">11: Chequeo de supuestos</a>
      </li>

      
      <li >
        <a href="/example/12-practico/">12: Errores de medida y procesamiento</a>
      </li>

      
      <li >
        <a href="/example/13-practico/">13: Omisión de variables relevantes</a>
      </li>

      
    </ul>
    

  </div>
  
  
</nav>

        </div>

        
        <div class="d-none d-xl-block col-xl-2 docs-toc">
            <ul class="nav toc-top">
                <li><a href="#" id="back_to_top" class="docs-toc-title">Contents</a></li>
            </ul>

            

 
        </div>
        

        <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 docs-content" role="main">

            <article class="article">

                <div class="docs-article-container">
                    <h1>Regresión lineal múltiple</h1>

                    

                    

                    

                    <div class="article-style">
                        

<div id="TOC">

</div>

<div id="objetivo-del-práctico" class="section level2">
<h2>0. Objetivo del práctico</h2>
<p>El presente práctico tiene dos objetivos:</p>
<ol style="list-style-type: decimal">
<li><p>Comprender las implicancias de la incorporación de más de un predictor en modelos de regresión lineal.</p></li>
<li><p>Aprender a estimar una regresión lineal múltiple en R con <code>lm()</code>.</p></li>
</ol>
<div id="materiales-de-la-sesión" class="section level3">
<h3>Materiales de la sesión</h3>
<p>Tal como en la sesión anterior, en este práctico se utilizarán los datos sobre <strong>salarios</strong> utilizados en el capítulo 2 del libro <em>Introducción a la econometría</em> de J.W. Wooldridge (2015).</p>
<p>Asimismo, la realización de este práctico requiere la carga de diversos <strong>paquetes</strong> que nos permitirán explorar los datos y presentar los modelos estimados.</p>
<pre class="r"><code>if (!require(&quot;pacman&quot;)) install.packages(&quot;pacman&quot;) # Instalamos pacman en caso de necesitarlo
pacman::p_load(wooldridge, #Para descargar los datos
               dplyr, #Para procesar datos
               sjmisc, #Para explorar los datos
               sjPlot, #Para explorar los datos
               srvyr, #Para crear un objeto encuesta
               survey, #Para realizar estimaciones incorporando el diseño muestral
               texreg) #Para presentar el modelo de regresión estimado
data(&quot;wage1&quot;) #Cargamos los datos
wage1 = select(wage1, wage, educ, exper) #Seleccionamos sólo las variables por analizar</code></pre>
</div>
</div>
<div id="volviendo-a-explorar-los-datos" class="section level2">
<h2>1. Volviendo a explorar los datos</h2>
<p>Si bien en este práctico volveremos a analizar el efecto de los años de escolaridad sobre los salarios por hora, ahora incorporaremos una nueva variable explicativa: los años de experiencia laboral.</p>
<ul>
<li><strong>wage</strong> (<span class="math inline">\(y\)</span>): indica el salario por hora en miles de pesos de cada persona en los datos.</li>
<li><strong>educ</strong> (<span class="math inline">\(x_1\)</span>): indica el número de años de escolaridad de cada persona en los datos.</li>
<li><strong>exper</strong> (<span class="math inline">\(x_2\)</span>): indica los años de experiencia laboral de cada persona en los datos.</li>
</ul>
<p>Las seleccionaremos utilizando la función <code>select()</code> de <code>dplyr</code>, a modo de trabajar con un set de datos más acotado</p>
<pre class="r"><code>wage1 = select(wage1, wage, educ, exper) #Seleccionamos sólo las variables por analizar</code></pre>
<p>Recordemos la distribución de estas variables:</p>
<p><img src="/example/06-practico_files/figure-html/plot_wage-1.png" width="672" /></p>
<p><img src="/example/06-practico_files/figure-html/plot_educ-1.png" width="672" /></p>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_bar).</code></pre>
<p><img src="/example/06-practico_files/figure-html/plot_exper-1.png" width="672" /></p>
<p>En este caso, la variable por explicar sigue siendo <strong>wage</strong> (<span class="math inline">\(y\)</span>), a partir de la cual estimaremos un modelo de <strong>regresión lineal múltiple</strong> sobre <strong>educ</strong> (<span class="math inline">\(x_1\)</span>) y <strong>exper</strong> (<span class="math inline">\(x_2\)</span>). Un modelo de regresión lineal múltiple se puede expresar a partir de la siguiente ecuación:</p>
<p><span class="math display">\[
\begin{equation}
\hat{y} = \beta_0 + \beta_1x_{i1} + \beta_2x_{i2}
\end{equation}
\]</span>
Donde</p>
<ul>
<li><p><span class="math inline">\(\beta_0\)</span>: Corresponde al intercepto de regresión.</p></li>
<li><p><span class="math inline">\(\beta_1\)</span>: Corresponde a la <strong>pendiente</strong> estimada para la función de regresión lineal de los <strong>salarios por hora</strong> (<span class="math inline">\(y\)</span>) sobre los <strong>años de escolaridad</strong> (<span class="math inline">\(x_1\)</span>). Así, por cada unidad que aumente <span class="math inline">\(x_1\)</span> (en este caso, por cada año de escolaridad extra), el valor estimado <span class="math inline">\(\hat{y}\)</span> para los salarios por hora aumentará o disminuirá en <span class="math inline">\(\beta_1\)</span>.</p></li>
<li><p><span class="math inline">\(\beta_2\)</span>: Corresponde a la <strong>pendiente</strong> estimada para la función de regresión lineal de los <strong>salarios por hora</strong> (<span class="math inline">\(y\)</span>) sobre los <strong>años de experiencia laboral</strong> (<span class="math inline">\(x_2\)</span>). Así, por cada unidad que aumente <span class="math inline">\(x_1\)</span> (en este caso, por cada año de experiencia laboral), el valor estimado <span class="math inline">\(\hat{y}\)</span> para los salarios por hora aumentará o disminuirá en <span class="math inline">\(\beta_2\)</span>.</p></li>
</ul>
<p>En este caso, se podría plantear la hipótesis de que tanto <strong>educ</strong> como <strong>exper</strong> debiesen tener un efecto positivo sobre <strong>wage</strong>. Es decir, que</p>
<ul>
<li><p>Quienes tengan más años de escolaridad debiesen tender, en promedio, valores predichos más altos que quienes tengan menos años de escolaridad. Así, se espera que <span class="math inline">\(\beta_1&gt;0\)</span>; y</p></li>
<li><p>Quienes tengan más años de experiencia laboral debiesen tender, en promedio, valores predichos más altos que quienes tengan menos años de experiencia laboral. Así, se espera que <span class="math inline">\(\beta_2&gt;0\)</span>.</p></li>
</ul>
<p>Como sabemos, existe una correlación de 0.41 entre salarios por hora y años de escolaridad:</p>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/example/06-practico_files/figure-html/plot_cor1-1.png" width="672" /></p>
<p>Por otra parte, esperamos que exista una asociación positiva entre salarios por hora y años de experiencia laboral</p>
<pre class="r"><code>sjPlot::plot_scatter(wage1, 
                     x = exper, 
                     y = wage,
                     title = &quot;Relación entre salarios (en miles de pesos) por hora y años de experiencia laboral&quot;,
                     fit.line = &quot;lm&quot;)</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/example/06-practico_files/figure-html/plot_cor2-1.png" width="672" /></p>
<p>Como podemos ver, la pendiente de la recta de regresión presentada no tiene una pendiente tan acentuada, lo cual sería indicativo de una baja relación entre ambas variables. Sin embargo, puede surgir la duda respecto de qué tan relacionadas están nuestras dos variables explicativas. Explorémoslo</p>
<pre class="r"><code>sjPlot::plot_scatter(wage1, 
                     x = educ, 
                     y = exper,
                     title = &quot;Relación entre años de escolaridad y años de experiencia laboral&quot;,
                     fit.line = &quot;lm&quot;)</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/example/06-practico_files/figure-html/plot_cor3-1.png" width="672" /></p>
<p>La siguiente tabla presenta los coeficientes de correlación de Pearson para todas las variables por analizar:</p>
<table style="border-collapse:collapse; border:none;">
<tr>
<th style="font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;">
 
</th>
<th style="font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;">
wage
</th>
<th style="font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;">
educ
</th>
<th style="font-style:italic; font-weight:normal; border-top:double black; border-bottom:1px solid black; padding:0.2cm;">
exper
</th>
</tr>
<tr>
<td style="font-style:italic;">
wage
</td>
<td style="padding:0.2cm; text-align:center;">
 
</td>
<td style="padding:0.2cm; text-align:center;">
 
</td>
<td style="padding:0.2cm; text-align:center;">
 
</td>
</tr>
<tr>
<td style="font-style:italic;">
educ
</td>
<td style="padding:0.2cm; text-align:center;">
0.406<span style="vertical-align:super;font-size:0.8em;">***</span>
</td>
<td style="padding:0.2cm; text-align:center;">
 
</td>
<td style="padding:0.2cm; text-align:center;">
 
</td>
</tr>
<tr>
<td style="font-style:italic;">
exper
</td>
<td style="padding:0.2cm; text-align:center;">
0.113<span style="vertical-align:super;font-size:0.8em;">**</span>
</td>
<td style="padding:0.2cm; text-align:center;">
-0.300<span style="vertical-align:super;font-size:0.8em;">***</span>
</td>
<td style="padding:0.2cm; text-align:center;">
 
</td>
</tr>
<tr>
<td colspan="4" style="border-bottom:double black; border-top:1px solid black; font-style:italic; font-size:0.9em; text-align:right;">
Computed correlation used pearson-method with listwise-deletion.
</td>
</tr>
</table>
<p>Como podemos ver, la asociación entre los años de experiencia laboral y los años de escolaridad es negativa y más fuerte que la correlación entre los primeros y el salario por hora. ¿Cómo puede esto afectar a la estimación de nuestro modelo? ¿qué efecto puede tener sobre la magnitud y el sentido de los coeficientes estimados? ¿cómo saber si vale la pena incorporar nuevas variables en el análisis? A continuación abordaremos todas estas inquietudes, retomando los conceptos que hemos estado revisando en las clases anteriores.</p>
</div>
<div id="estimando-modelos-de-regresión-lineal-simple-y-múltiple-con-lm" class="section level2">
<h2>2. Estimando modelos de regresión lineal simple y múltiple con <code>lm()</code></h2>
<p>En términos de código, la estimación de modelos de regresión lineal simple no distan mucho de la estimación de modelos de regresión lineal múltiple. Estimemos el modelo para salarios por hora sobre años de escolaridad</p>
<p><span class="math display">\[
\begin{equation}
\hat{wage} = \beta_0 + \beta_1educ_{i}
\end{equation}
\]</span></p>
<pre class="r"><code>m1 = lm(wage ~ educ, data = wage1)</code></pre>
<p>Luego, el modelo para salarios por hora sobre años de experiencia laboral</p>
<p><span class="math display">\[
\begin{equation}
\hat{wage} = \beta_0 + \beta_2exper_{i}
\end{equation}
\]</span></p>
<pre class="r"><code>m2 = lm(wage ~ exper, data = wage1)</code></pre>
<p>Por último, el modelo para salarios por hora sobre años de escolaridad y años de experiencia laboral</p>
<p><span class="math display">\[
\begin{equation}
\hat{wage} = \beta_0 + \beta_1educ_{i} + \beta_2exper_{i}
\end{equation}
\]</span></p>
<pre class="r"><code>m3 = lm(wage ~ educ + exper, data = wage1)</code></pre>
<p>Como podemos ver, la única diferencia entre la estimación de un modelo de regresión lineal simple y uno múltiple con <code>lm()</code> es la incorporación de todas las variables explicativas, una tras otra, separadas por <code>+</code> (signo más).</p>
<p>Comparemos los tres modelos:</p>
<pre><code>## 
## ===============================================
##              Modelo 1    Modelo 2    Modelo 3  
## -----------------------------------------------
## (Intercept)   -0.90        5.37 ***   -3.39 ***
##               (0.68)      (0.26)      (0.77)   
## educ           0.54 ***                0.64 ***
##               (0.05)                  (0.05)   
## exper                      0.03 **     0.07 ***
##                           (0.01)      (0.01)   
## -----------------------------------------------
## R^2            0.16        0.01        0.23    
## Adj. R^2       0.16        0.01        0.22    
## Num. obs.    526         526         526       
## ===============================================
## *** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
<p>Considerando las ecuaciones formuladas genéricamente más arriba, los modelos estimados se puede expresar así:</p>
<ul>
<li><strong>Modelo 1</strong>
<span class="math display">\[
\begin{equation}
\hat{wage} = -.9 + .54educ_{i}
\end{equation}
\]</span></li>
<li><strong>Modelo 2</strong></li>
</ul>
<p><span class="math display">\[
\begin{equation}
\hat{wage} = 5.37 + 0.03exper_{i}
\end{equation}
\]</span></p>
<ul>
<li><strong>Modelo 3</strong></li>
</ul>
<p><span class="math display">\[
\begin{equation}
\hat{wage} = -3.39 + .64educ_{i} + .07exper_{i}
\end{equation}
\]</span></p>
<p>Hay varias diferencias entre los tres modelos que podemos advertir:</p>
<ul>
<li><p>El valor del <strong>intercepto</strong> de regresión es distinto entre los tres modelos.</p></li>
<li><p>Los valores de los <strong>coeficientes de regresión</strong> estimados para ambas variables son diferentes al incorporar ambas variables en conjunto.</p></li>
<li><p>La bondad de ajuste de los tres modelos expresada a través del estadístico <span class="math inline">\(R^2\)</span> también difiere en los tres modelos, siendo mayor en el modelo 3 (<span class="math inline">\(R^2\)</span> = .22).</p></li>
<li><p>Mientras que en los modelos 1 y 2 los estadísticos <span class="math inline">\(R^2\)</span> y <span class="math inline">\(R^2\)</span> Ajustado (Adj. <span class="math inline">\(R^2\)</span>) son equivalentes, en el modelo 3 el valor de <span class="math inline">\(R^2\)</span> (.23) y <span class="math inline">\(R^2\)</span> Ajustado (.22) difieren en .01.</p></li>
</ul>
<p>De ello podemos deducir que:</p>
<ul>
<li>Los años de escolaridad permiten explicar mejor que los años de experiencia laboral los salarios por hora promedio. Esto, porque
<ul>
<li>El <span class="math inline">\(R^2\)</span> del modelo 1 (.16) es mayor que el del modelo 2 (.01).</li>
<li>La magnitud del coeficiente de regresión de años de escolaridad es mayor que la del coeficiente estimado para años de experiencia laboral.</li>
</ul></li>
<li>El efecto estimado de los años de escolaridad y años de experiencia laboral sobre los salarios por hora es positivo, tal como se planteó en la hipótesis al inicio del práctico.</li>
<li>El modelo 3 permite explicar mejor la variabilidad de <span class="math inline">\(y\)</span> que los modelos 2 y 1.</li>
<li>El valor estimado para el estadístico <span class="math inline">\(R^2\)</span> ajustado tiende a ser penalizado cuando se incorpora más de una variable explicativa; es decir, en modelos de regresión lineal múltiple, <span class="math inline">\(R^2 &gt; Adj.R^2\)</span>. Por eso, en modelos múltiples es preferible evaluar la bondad de ajuste en base al estadístico ajustado, en la medida que es un criterio más estricto para definir qué tan bien las variables explicativas en su conjunto permiten explicar la variabilidad de <span class="math inline">\(y\)</span>.</li>
</ul>
<p>¿Por qué sucede todo esto al incorporar una nueva variable explicativa? Para comprenderlo, recurriremos al concepto de <strong>parcialización</strong>.</p>
</div>
<div id="la-parcialización" class="section level2">
<h2>3. La parcialización</h2>
<p>Como pudimos ver anteriormente, <strong>educ</strong> está correlacionado negativa y moderadamente (R = -.3) con <strong>exper</strong>. Esto tiene como consecuencia que una parte del efecto de <strong>educ</strong> sobre <strong>wage</strong> es compartida por <strong>exper</strong>, y viceversa, lo cual genera cambios tanto en la estimación de los coeficientes de regresión como en la bondad de ajuste. Recordemos que lo que esperamos hacer con un modelo de estas características es aislar el efecto de <span class="math inline">\(x_1,x_2,...,x_n\)</span> sobre <span class="math inline">\(y\)</span>. Es decir: poder analizar el efecto de <span class="math inline">\(x_1\)</span> sobre <span class="math inline">\(y\)</span>, manteniendo constante el efecto del resto de variables involucradas en la variabilidad de <span class="math inline">\(y\)</span>. Considerando nuestro <strong>modelo 3</strong> <span class="math inline">\(\hat{wage} = -3.39 + .64educ_{i} + .07exper_{i}\)</span>, ello se leería de la siguiente manera:</p>
<ul>
<li><p>Por cada año de escolaridad adicional se espera que, en promedio, el salario por hora predicho aumente en .64 mil pesos, sin importar los años de experiencia que tenga la persona. Así, una persona con 20 años de experiencia, pero con 17 años de escolaridad debiese percibir un salario por hora promedio de 8.89 mil pesos; mientras se espera que, en promedio, alguien con los mismos años de experiencia laboral y 12 años de escolaridad obtenga un salario por hora de 5.69 mil pesos, lo cual expresa una diferencia media de 3.2 mil pesos.</p></li>
<li><p>Por cada año de experiencia laboral adicional se espera que, en promedio, el salario por hora predicho aumente en .07 mil pesos, sin importar los años de experiencia que tenga la persona. Así, una persona con 12 años de escolaridad, pero con 20 años de experiencia laboral debiese percibir un salario por hora promedio de 5.69 mil pesos; mientras se espera que, en promedio, alguien con los mismos años de escolaridad y 10 años de experiencia laboral obtenga un salario por hora de 4.99 mil pesos, lo cual expresa una diferencia media de 0.7 mil pesos.</p></li>
</ul>
<p>Para poder realizar un análisis “manteniendo constante el efecto del resto de factores”, empleamos el procedimiento de <strong>parcialización</strong>, que consiste en remover la <strong>covarianza común</strong> que existe entre los predictores. A ello se le denomina <strong>efecto parcial</strong>, en la medida que estima regresión considerando solamente el efecto de <span class="math inline">\(x_n\)</span> sobre <span class="math inline">\(y\)</span> que no es compartido con los otros predictores.
¿Cómo saber cuál es la magnitud del efecto común a ambas variables y extraerlo? Para ello podemos modelar una regresión simple en que los predictores son las variables del modelo. En este caso, estimar un modelo que mida el efecto de <strong>educ</strong> sobre <strong>exper</strong>. Ello nos permitirá calcular, a su vez, los <strong>residuos</strong> del modelo entre las variables explicativas, que representa la parte de <span class="math inline">\(x_1\)</span> que no es explicada por <span class="math inline">\(x_2\)</span>. A su vez, el coeficiente de regresión <span class="math inline">\(\beta_1\)</span> representa todo lo compartido entre <strong>educ</strong> y <strong>exper</strong>. Estimemos el modelo:</p>
<pre class="r"><code>mod_p = lm(educ ~ exper, wage1)
summary(mod_p)</code></pre>
<pre><code>## 
## Call:
## lm(formula = educ ~ exper, data = wage1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -12.258  -1.358  -0.236   1.721   6.170 
## 
## Coefficients:
##              Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept) 13.602708   0.185024  73.519 &lt; 0.0000000000000002 ***
## exper       -0.061113   0.008504  -7.187      0.0000000000023 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.644 on 524 degrees of freedom
## Multiple R-squared:  0.08973,    Adjusted R-squared:  0.08799 
## F-statistic: 51.65 on 1 and 524 DF,  p-value: 0.000000000002295</code></pre>
<p>Así</p>
<p><span class="math display">\[
\begin{equation}
\hat{educ} = 13.60 + 0.06exper_{i}
\end{equation}
\]</span></p>
<p>Estimemos los <strong>residuos</strong> para cada observación; es decir, la diferencia entre el valor predicho y el observado que, en este caso, representa la varianza no explicada de los años de experiencia laboral sobre los años de escolaridad.</p>
<pre class="r"><code>pred = fitted.values(mod_p)
res = residuals(mod_p)
wage1 = cbind(wage1, pred, res)</code></pre>
<p>Ahora hagamos una regresión lineal de <strong>wage</strong> sobre los <strong>residuos</strong> estimados para el modelo de <strong>educ</strong> sobre <strong>exper</strong></p>
<pre class="r"><code>mod_res = lm(wage ~ res, wage1)
screenreg(list(m3, mod_res), custom.model.names = c(&quot;Modelo 3&quot;, &quot;Modelo 4&quot;))</code></pre>
<pre><code>## 
## ===================================
##              Modelo 3    Modelo 4  
## -----------------------------------
## (Intercept)   -3.39 ***    5.90 ***
##               (0.77)      (0.14)   
## educ           0.64 ***            
##               (0.05)               
## exper          0.07 ***            
##               (0.01)               
## res                        0.64 ***
##                           (0.05)   
## -----------------------------------
## R^2            0.23        0.21    
## Adj. R^2       0.22        0.21    
## Num. obs.    526         526       
## ===================================
## *** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
<p>Podemos ver que el coeficiente estimado para <strong>educ</strong> en el modelo 3 es igual que aquel estimada para el modelo 4. Es decir, el <strong>coeficiente parcializado</strong> para los años de escolaridad estimado en el modelo 3 representa el efecto de la parte de <strong>educ</strong> que no es explicada por <strong>exper</strong> sobre <strong>wage</strong>. Como pueden haber intuido, la parcialización es un procedimiento que <code>lm()</code> realiza automáticamente a la hora de estimar los modelos, pese a lo cual es <strong>fundamental</strong> comprenderlo adecuadamente para poder entender qué significa analizar el efecto de <span class="math inline">\(x_n\)</span> sobre <span class="math inline">\(y\)</span> <em>ceteris paribus</em>.</p>
<p>En síntesis: la parcialización nos permite estimar y analizar el <strong>efecto parcial</strong> de <span class="math inline">\(x_n\)</span> sobre <span class="math inline">\(y\)</span>, <strong>controlando</strong> el efecto de otras variables sobre <span class="math inline">\(y\)</span>.</p>
</div>
<div id="resumen" class="section level2">
<h2>Resumen</h2>
<p>En este práctico aprendimos las diferencias existentes entre modelos de regresión lineal simple y múltiple, poniendo especial atención al concepto de <strong>parcialización</strong>.</p>
</div>

                    </div>

                    



                    
                    <div class="article-widget">
                        
<div class="post-nav">
  
  
  
  <div class="post-nav-item">
    <div class="meta-nav">Previous</div>
    <a href="/example/05-practico/" rel="next">Regresión lineal simple con diseño muestral y bondad de ajuste</a>
  </div>
  
  
  
  <div class="post-nav-item">
    <div class="meta-nav">Next</div>
    <a href="/example/07-practico/" rel="prev">Regresión lineal múltiple y predictores categóricos</a>
  </div>
  
</div>

                    </div>
                    
                </div>

                <div class="body-footer">
                    <p>Last updated on January 1, 0001</p>

                    





                    



                </div>

            </article>

            <footer>
    <hr>

    <div class="row course-info">
        <div class="col-md-7">
            <p>
                <strong>: Estadística II (I° Semestre- 2023)</strong><br>

                <a href="https://www.uahurtado.cl/" target="_blank" rel="noopener">Universidad Alberto Hurtado</a> &emsp;&emsp;
                <a href="https://www.uahurtado.cl/carreras/ciencia-politica/" target="_blank" rel="noopener">Departamento de Ciencia Política y Relaciones Internacionales</a>
            </p>

            <p>
                <a href="https://valentinaandrade.netlify.app/" target="_blank" rel="noopener"><i class="fas fa-user"></i>
                    Valentina Andrade</a> &emsp;&emsp;
                <a href="mailto:valentinaandrade@uchile.cl"><i class="fas fa-envelope"></i>
                    valentinaandrade@uchile.cl</a>
            </p>

            <p>
                <i class="far fa-calendar-alt"></i> Clases: Martes o Jueves (1 bloque) &emsp;&emsp;
                <i class="fas fa-pencil-alt"></i> Práctico: Martes o Jueves (2 bloque) 
                <br><i class="fas fa-university"></i> Sala por definir
            </p>
        </div>

        <div class="col-md-5 credits">
            <p>All content licensed under a <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" rel="noopener">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.</p>
            
            <p>Content <i class="fab fa-creative-commons"></i> 2023. Web developed by Andrew Heiss and custom by <a href="https://valentinaandrade.netlify.app/" target="_blank" rel="noopener">Valentina Andrade</a></p>
        
            <p>This site created with the <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> in <a href="https://bookdown.org/yihui/blogdown/" target="_blank" rel="noopener">blogdown</a> and <a href="https://gohugo.io/" target="_blank" rel="noopener">Hugo</a>. </p>
            
            <p><a href="https://github.com/valentinaandrade" target="_blank" rel="noopener"><i class="fab fa-github"></i> View the source at GitHub.</a></p>
        </div>
    </div>
</footer>


        </main>
    </div>
</div>

        

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/instant.page/5.1.0/instantpage.min.js" integrity="sha512-1+qUtKoh9XZW7j+6LhRMAyOrgSQKenQ4mluTR+cvxXjP1Z54RxZuzstR/H9kgPXQsVB8IW7DMDFUJpzLjvhGSQ==" crossorigin="anonymous"></script>

      
      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      

      
      

      

      

    

    
    
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.2.2/anchor.min.js" integrity="sha512-I7w3ZdSFzw5j3jU3ZkNikBNeIrl3i+hEuEdwNmqUJvwNcaBUNcijnP2gd9DtGlgVYDplfjGoD8vTNsID+lCjqg==" crossorigin="anonymous"></script>
    <script>
      anchors.add();
    </script>
    

    
    
    

    
    

    
    
    
    

    
    <script src="/js/bootstrap.bundle.min.8b7df62fd2da18ce73e29c13cc0a6198.js"></script>

    
    

    
    
    
    
    
    
    
    
    
    <script src="/en/js/wowchemy.min.c6ceb5c48772e46156651a48070d6139.js"></script>

    

<script src="/js/math-code.js"></script>


    
    

    
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>

</html>
