<!DOCTYPE html>
<html lang="en-us" 
      xmlns:og="http://ogp.me/ns#" 
      xmlns:fb="https://www.facebook.com/2008/fbml">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  
  
  
    <meta name="generator" content="Wowchemy 5.2.0 for Hugo" />
  

  

  
  
  
  
  
  

  

  
  
  
    
  
  <meta name="description" content="0. Objetivo del prácticoEl objetivo de este práctico es aprender a generar e interpretar modelos con transformaciones cuadrática y logarítmica en las variables \(x\) e \(y\) con lm()." />

  
  <link rel="alternate" hreflang="en-us" href="/example/09-practico/" />

  







  




  
  
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  

  
  
  
    <meta name="theme-color" content="#1a9875" />
  

  
  
    
    <script src="/js/mathjax-config.js"></script>
  

  
  
  
  
    
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha256-FMvZuGapsJLjouA6k7Eo2lusoAX9i0ShlWFG6qt7SLc=" crossorigin="anonymous">

    
    

    
    
    
      
    
    

    
    
    

    

    
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" integrity="" crossorigin="anonymous" async></script>
      
    
      
      

      
      

      
    
      
      

      
      

      
    
  

  
  
  
    
      
      
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Fira+Sans+Condensed:400,400i,700,700i%7CBarlow:ital,wght@0,400;0,700;1,400;1,700&display=swap">
      
    
  

  
  
  
  
  
  <link rel="stylesheet" href="/css/wowchemy.6c40d5e91ad0908cd1753452468e8c67.css" />

  



  

  

  




  
  
  

  

  
    <link rel="manifest" href="/index.webmanifest" />
  

  <link rel="icon" type="image/png" href="/media/icon_hua2ec155b4296a9c9791d015323e16eb5_11927_32x32_fill_lanczos_center_2.png" />
  <link rel="apple-touch-icon" type="image/png" href="/media/icon_hua2ec155b4296a9c9791d015323e16eb5_11927_180x180_fill_lanczos_center_2.png" />

  <link rel="canonical" href="/example/09-practico/" />

  
  
  
  
  
  
  
  
    
    
  
  
  <meta property="twitter:card" content="summary" />
  
    <meta property="twitter:site" content="@valentiandrade" />
    <meta property="twitter:creator" content="@valentiandrade" />
  
  <meta property="og:site_name" content="Estadística II" />
  <meta property="og:url" content="/example/09-practico/" />
  <meta property="og:title" content="Transformaciones funcionales | Estadística II" />
  <meta property="og:description" content="0. Objetivo del prácticoEl objetivo de este práctico es aprender a generar e interpretar modelos con transformaciones cuadrática y logarítmica en las variables \(x\) e \(y\) con lm()." /><meta property="og:image" content="/media/logo_huec1c53a9c99ba801c510916ffbd8bc18_109138_300x300_fit_lanczos_2.png" />
    <meta property="twitter:image" content="/media/logo_huec1c53a9c99ba801c510916ffbd8bc18_109138_300x300_fit_lanczos_2.png" /><meta property="og:locale" content="en-us" />
  
    
    
  

  



  

  

  <link rel="stylesheet" type="text/css" href="/custom-css/print.css" media="print" />

  <link rel="shortcut icon" href="/favicon.ico" />
  <link rel="apple-touch-icon-precomposed" sizes="57x57" href="/img/apple-touch-icon-57x57.png" />
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/img/apple-touch-icon-114x114.png" />
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/img/apple-touch-icon-72x72.png" />
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/img/apple-touch-icon-144x144.png" />
  <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/img/apple-touch-icon-120x120.png" />
  <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/img/apple-touch-icon-152x152.png" />
  <link rel="icon" type="image/png" href="/img/favicon-32x32.png" sizes="32x32" />
  <link rel="icon" type="image/png" href="/img/favicon-16x16.png" sizes="16x16" />
  <meta name="application-name" content=": Estadística II" />
  <meta name="msapplication-TileColor" content="#FFFFFF" />
  <meta name="msapplication-TileImage" content="/img/mstile-144x144.png" />


  <title>Transformaciones funcionales | Estadística II</title>
</head>


<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" class="page-wrapper  ">

  
  
  
  
  
  <script src="/js/wowchemy-init.js"></script>

    




    











  


<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container-xl">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/"><img src="/media/logo_huec1c53a9c99ba801c510916ffbd8bc18_109138_0x70_resize_lanczos_2.png" alt="Estadística II"></a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar-content" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/"><img src="/media/logo_huec1c53a9c99ba801c510916ffbd8bc18_109138_0x70_resize_lanczos_2.png" alt="Estadística II"></a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-end" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"><span>Organización</span><span class="caret"></span>
          </a>
          <div class="dropdown-menu">
            
              <a class="dropdown-item" href="/schedule/"><span>Planificación</span></a>
            
              <a class="dropdown-item" href="/syllabus/"><span>Syllabus</span></a>
            
          </div>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/content/"><span>Clases</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link  active" href="/example/"><span>Prácticos</span></a>
        </li>

        
        

        
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"><span>Evaluaciones <i class="fab fa-github"></i></span><span class="caret"></span>
          </a>
          <div class="dropdown-menu">
            
              <a class="dropdown-item" href="/assignment/"><span>Controles</span></a>
            
              <a class="dropdown-item" href="https://classroom.github.com/classrooms/86887318-learn-r-uah-2021"><span>Github Classroom<i class="fab fa-github"></i></span></a>
            
          </div>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/resource/"><span>Recursos</span></a>
        </li>

        
        

        

        
        
        
          
            
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="https://join.slack.com/t/estadisticaii-uah/shared_invite/zt-1qi7am4o2-7pVVgPC~s0IcBKwqSRWSvQ" target="_blank" rel="noopener"><span><i class="fab fa-slack"></i></span></a>
        </li>

        
        

        

        
        
        
          
            
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="https://rstudio.cloud/" target="_blank" rel="noopener"><span><i class="fab fa-r-project"></i></span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">

      
      

      
      

      
      

      
      

    </ul>

  </div>
</nav>



    

<div class="container-fluid docs">
    <div class="row flex-xl-nowrap">
        <div class="col-12 col-md-3 col-xl-2 docs-sidebar">
            





  
    
  




<form class="docs-search d-flex align-items-center">
  <button class="btn docs-toggle d-md-none p-0 mr-3" type="button" data-toggle="collapse" data-target="#docs-nav" aria-controls="docs-nav" aria-expanded="false" aria-label="Toggle section navigation">
    <span><i class="fas fa-bars"></i></span>
  </button>

  
</form>

<nav class="collapse docs-links" id="docs-nav">
  

  
  
  
    
  

  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/example/">Información general</a>
    <ul class="nav docs-sidenav">
      
      <li >
        <a href="/example/">Prácticos (códigos de ejemplo)</a>
      </li>

      
    </ul>
    

  </div>
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" >Datos</a>

  </div>
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/example/01-practico/">Ejemplos</a>
    <ul class="nav docs-sidenav">
      
      <li >
        <a href="/example/01-practico/">1: Variables aleatorias y distribuciones</a>
      </li>

      
      <li >
        <a href="/example/02-practico/">2: Inferencia</a>
      </li>

      
      <li >
        <a href="/example/032-practico/">3: RMarkdown</a>
      </li>

      
      <li >
        <a href="/example/03-practico/">3: R, RStudio y Github</a>
      </li>

      
      <li >
        <a href="/example/04-practico/">4: Regresión lineal simple</a>
      </li>

      
      <li >
        <a href="/example/05-practico/">5: Regresión lineal simple con diseño muestral y bondad de ajuste</a>
      </li>

      
      <li >
        <a href="/example/06-practico/">6: Regresión lineal múltiple</a>
      </li>

      
      <li >
        <a href="/example/07-practico/">7: Regresión lineal múltiple y predictores categóricos</a>
      </li>

      
      <li >
        <a href="/example/08-practico/">8: Inferencia y predicción</a>
      </li>

      
      <li class="active">
        <a href="/example/09-practico/">9: Transformaciones funcionales</a>
      </li>

      
      <li >
        <a href="/example/10-practico/">10: Relaciones no lineales y términos de interacción</a>
      </li>

      
      <li >
        <a href="/example/11-practico/">11: Chequeo de supuestos</a>
      </li>

      
      <li >
        <a href="/example/12-practico/">12: Errores de medida y procesamiento</a>
      </li>

      
      <li >
        <a href="/example/13-practico/">13: Omisión de variables relevantes</a>
      </li>

      
    </ul>
    

  </div>
  
  
</nav>

        </div>

        
        <div class="d-none d-xl-block col-xl-2 docs-toc">
            <ul class="nav toc-top">
                <li><a href="#" id="back_to_top" class="docs-toc-title">Contents</a></li>
            </ul>

            

 
        </div>
        

        <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 docs-content" role="main">

            <article class="article">

                <div class="docs-article-container">
                    <h1>Transformaciones funcionales</h1>

                    

                    

                    

                    <div class="article-style">
                        

<div id="TOC">

</div>

<div id="objetivo-del-práctico" class="section level2">
<h2>0. Objetivo del práctico</h2>
<p>El objetivo de este práctico es aprender a generar e interpretar modelos con transformaciones cuadrática y logarítmica en las variables <span class="math inline">\(x\)</span> e <span class="math inline">\(y\)</span> con <code>lm()</code>.</p>
<div id="materiales-de-la-sesión" class="section level3">
<h3>Materiales de la sesión</h3>
<p>Tal como en la sesión anterior, en este práctico se utilizarán los datos sobre <strong>precios de casas</strong> utilizados en el capítulo 6 del libro <em>Introducción a la econometría</em> de J.W. Wooldridge (2015). En este caso, cargaremos los datos ya procesados. Asimismo, la realización de este práctico requiere la carga de diversos <strong>paquetes</strong> que nos permitirán explorar los datos y presentar los modelos estimados.</p>
<pre class="r"><code>if (!require(&quot;pacman&quot;)) install.packages(&quot;pacman&quot;) # Instalamos pacman en caso de necesitarlo</code></pre>
<pre><code>## Loading required package: pacman</code></pre>
<pre class="r"><code>pacman::p_load(wooldridge, #Para descargar los datos
               dplyr, #Para procesar datos
               ggplot2,#Para graficar
               sjmisc, #Para explorar los datos
               sjPlot, #Para explorar los datos
               texreg) #Para presentar el modelo de regresión estimado
data(&quot;hprice2&quot;)</code></pre>
</div>
</div>
<div id="explorando-los-datos" class="section level2">
<h2>1. Explorando los datos</h2>
<p>Esta vez trabajaremos con los datos <code>hprice2</code> sobre precios de casas y medio ambiente. En específico, utilizaremos las variables</p>
<p>Volvemos a encontrarnos con:</p>
<ul>
<li><strong>price</strong> (<span class="math inline">\(y\)</span>): indica el precio mediano de las casas en cada comunidad.</li>
<li><strong>nox</strong> (<span class="math inline">\(x_1\)</span>): indica la concentración de óxido nitroso de la comunidad en partes por 100 millones.</li>
<li><strong>rooms</strong> (<span class="math inline">\(x_2\)</span>): indica la media de habitaciones por vivienda en la comunidad.</li>
</ul>
<p>También utilizaremos el logaritmo de las dos primeras variables variables: <strong>lprice</strong>, <strong>lnox</strong>.</p>
<p>Generemos el modelo con <code>lm()</code>, y visualicémoslo</p>
<pre class="r"><code>m1 = lm(price ~ nox + rooms, data = hprice2)
screenreg(m1, custom.model.names = &quot;Modelo 1&quot;)</code></pre>
<pre><code>## 
## ==========================
##              Modelo 1     
## --------------------------
## (Intercept)  -18423.40 ***
##               (3346.66)   
## nox           -1884.68 ***
##                (253.57)   
## rooms          8178.56 ***
##                (418.08)   
## --------------------------
## R^2               0.54    
## Adj. R^2          0.53    
## Num. obs.       506       
## ==========================
## *** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
<p>Podemos ver que, mientras el efecto de la concentración de óxido nitroso sobre el precio mediano de las casas es negativo, el número de habitaciones tiene un efecto positivo sobre el precio mediano de tales. Además, en conjunto, ambas variables explican en torno al 53% de la varianza del precio mediano de las casas.</p>
</div>
<div id="las-transformaciones-funcionales-la-transformación-funcional-logarítmica" class="section level2">
<h2>2. Las transformaciones funcionales: la transformación funcional logarítmica</h2>
<p>Muchas veces es posible que las relaciones que existen entre nuestra variable explicada y nuestras variables explicativas no es lineal. Para subsanar este problema, recurriremos a diversas fórmulas, una de las cuales es la <strong>transformación logarítmica</strong>. En las siguientes clases estaremos revisando otras dos: la transformación funcional <strong>cuadrática</strong>, y las <strong>interacciones</strong> entre variables explicativas.</p>
<p>Para la transformación funcional logarítmica, simplemente tenemos que incorporar, bien como variables predictoras o predichas, el <strong>logaritmo natural</strong>. Por supuesto, esto sólo aplica para variables numéricas: no es posible ejecutar una transformación funcional logarítmica a una variable cualitativa.</p>
<p>Consideremos los parámetros del modelo original:</p>
<p><span class="math display">\[
\begin{equation}
price = \beta_0 + \beta_1nox + \beta_2rooms
\end{equation}
\]</span></p>
<p>Al interpretar este modelo, podemos señalar que, por cada unidad que varíe <span class="math inline">\(nox\)</span>, el valor predicho para <span class="math inline">\(price\)</span> aumentará o disminuirá en <span class="math inline">\(\beta_1\)</span> unidades. Cuando aplicamos transformaciones funcionales logarítmicas, las variaciones y el efecto se deben interpretar <strong>porcentualmente</strong>, según corresponda.</p>
<p>Una de las limitaciones de esta transformacional funcional es que no puede utilizarse si una variable toma valores negativos o cero.</p>
<div id="a-transformación-funcional-logarítmica-a-variable-x" class="section level3">
<h3>a) Transformación funcional logarítmica a variable <span class="math inline">\(x\)</span></h3>
<p>Una de las variaciones que podemos realizar es estimar el modelo transformando logarítmicamente uno de sus predictores. En este caso, implementaremos la transformación funcional sobre <span class="math inline">\(nox\)</span>.</p>
<p><span class="math display">\[
\begin{equation}
price = \beta_0 + \beta_1log(nox) + \beta_2rooms
\end{equation}
\]</span></p>
<p>Estimemos el modelo con <code>lm()</code> y comparemos con el modelo original:</p>
<pre class="r"><code>m2 = lm(price ~ lnox + rooms, data = hprice2)
screenreg(list(m1,m2), custom.model.names = c(&quot;Modelo 1&quot;, &quot;Modelo 2&quot;))</code></pre>
<pre><code>## 
## =========================================
##              Modelo 1       Modelo 2     
## -----------------------------------------
## (Intercept)  -18423.40 ***  -10237.60 *  
##               (3346.66)      (4125.88)   
## nox           -1884.68 ***               
##                (253.57)                  
## rooms          8178.56 ***    8162.07 ***
##                (418.08)       (417.94)   
## lnox                        -10951.41 ***
##                              (1457.92)   
## -----------------------------------------
## R^2               0.54           0.54    
## Adj. R^2          0.53           0.53    
## Num. obs.       506            506       
## =========================================
## *** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
<p>En este caso, ambos modelos presentan los mismos valores en <span class="math inline">\(R^2\)</span> y <span class="math inline">\(R^2\)</span> ajustado. No obstante, es posible apreciar que los coeficientes de <span class="math inline">\(nox\)</span> y <span class="math inline">\(log(nox)\)</span> son diferentes. Lo mismo sucede con los coeficientes estimados para <span class="math inline">\(rooms\)</span>, que no analizaremos en este ejemplo. Interpretemos los dos primeros por separado:</p>
<ul>
<li><span class="math inline">\(nox\)</span>: por cada unidad que aumente <span class="math inline">\(nox\)</span>, se espera que el precio mediano de las casas en cada comunidad disminuya en 1884.68 dólares en promedio.</li>
<li><span class="math inline">\(lnox\)</span>: por cada punto porcentual (1%) que aumente <span class="math inline">\(lnox\)</span>, se espera que el precio mediano de las casas disminuya, en promedio, 10951.41 dólares.</li>
</ul>
</div>
<div id="b-transformación-funcional-logarítmica-a-variable-y" class="section level3">
<h3>b) Transformación funcional logarítmica a variable <span class="math inline">\(y\)</span></h3>
<p>¿Y si, en lugar de transformar logarítmicamente al predictor, lo hacemos con la variable predicha?</p>
<p><span class="math display">\[
\begin{equation}
log(price) = \beta_0 + \beta_1nox + \beta_2rooms
\end{equation}
\]</span></p>
<pre class="r"><code>m3 = lm(lprice ~ nox + rooms, data = hprice2)
screenreg(list(m1,m2, m3), custom.model.names = c(&quot;Modelo 1&quot;, &quot;Modelo 2&quot;, &quot;Modelo 3&quot;))</code></pre>
<pre><code>## 
## =====================================================
##              Modelo 1       Modelo 2       Modelo 3  
## -----------------------------------------------------
## (Intercept)  -18423.40 ***  -10237.60 *      8.70 ***
##               (3346.66)      (4125.88)      (0.15)   
## nox           -1884.68 ***                  -0.12 ***
##                (253.57)                     (0.01)   
## rooms          8178.56 ***    8162.07 ***    0.31 ***
##                (418.08)       (417.94)      (0.02)   
## lnox                        -10951.41 ***            
##                              (1457.92)               
## -----------------------------------------------------
## R^2               0.54           0.54        0.51    
## Adj. R^2          0.53           0.53        0.51    
## Num. obs.       506            506         506       
## =====================================================
## *** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
<p>En este caso, podemos darnos cuenta de dos cosas fundamentales:</p>
<ul>
<li>La magnitud de los coeficientes ha disminuido bastante. Esto se debe a que, ahora, las variaciones por unidad de <span class="math inline">\(x\)</span> tendrán un efecto <strong>porcentual</strong> en la variación media de <span class="math inline">\(y\)</span>.</li>
<li>Los estadísticos <span class="math inline">\(R^2\)</span> de este último modelo son levemente inferiores que los estimados para los modelos previos. Esto nos indica que transformar funcionalmente las variables incorporadas en nuestro modelo puede afectar también su bondad de ajuste.</li>
</ul>
<p>Así, podemos señalar que, por cada unidad que aumenta el promedio de habitaciones en las casas de cada comunidad, se espera que el precio de estas aumente, en promedio, un 31%. En estos casos denominamos a <span class="math inline">\(\beta_2*100\)</span> como <strong>semielasticidad</strong> de <span class="math inline">\(price\)</span> respecto a <span class="math inline">\(rooms\)</span>. No obstante, a medida que la variación de <span class="math inline">\(log(y)\)</span> aumenta, se incrementa el error de aproximación que se realiza al estimar el efecto como %<span class="math inline">\(\vartriangle y \approx 100*\vartriangle log(y)\)</span>. Para ello, debemos ejecutar el siguiente procedimiento:</p>
<p><span class="math display">\[
\begin{equation}
\%\vartriangle \hat{y} = 100 * [exp(\beta x) - 1]
\end{equation}
\]</span></p>
<p>En este caso:</p>
<p><span class="math display">\[
\begin{equation}
\%\vartriangle \hat{y} = 100 * [exp(.31*1) - 1] = 100 * [1.363-1] = 100* 0.363 = 36.3 \%
\end{equation}
\]</span></p>
</div>
<div id="c-transformación-funcional-logarítmica-a-variable-x-e-y" class="section level3">
<h3>c) Transformación funcional logarítmica a variable <span class="math inline">\(x\)</span> e <span class="math inline">\(y\)</span></h3>
<p>Por último, podemos incluso transformar funcionalmente a nuestras variables explicativas y explicada:</p>
<p><span class="math display">\[
\begin{equation}
log(price) = \beta_0 + \beta_1log(nox) + \beta_2rooms
\end{equation}
\]</span></p>
<pre class="r"><code>m4 = lm(lprice ~ lnox + rooms, data = hprice2)
screenreg(list(m1,m2, m3, m4), custom.model.names = c(&quot;Modelo 1&quot;, &quot;Modelo 2&quot;, &quot;Modelo 3&quot;, &quot;Modelo 4&quot;))</code></pre>
<pre><code>## 
## =================================================================
##              Modelo 1       Modelo 2       Modelo 3    Modelo 4  
## -----------------------------------------------------------------
## (Intercept)  -18423.40 ***  -10237.60 *      8.70 ***    9.23 ***
##               (3346.66)      (4125.88)      (0.15)      (0.19)   
## nox           -1884.68 ***                  -0.12 ***            
##                (253.57)                     (0.01)               
## rooms          8178.56 ***    8162.07 ***    0.31 ***    0.31 ***
##                (418.08)       (417.94)      (0.02)      (0.02)   
## lnox                        -10951.41 ***               -0.72 ***
##                              (1457.92)                  (0.07)   
## -----------------------------------------------------------------
## R^2               0.54           0.54        0.51        0.51    
## Adj. R^2          0.53           0.53        0.51        0.51    
## Num. obs.       506            506         506         506       
## =================================================================
## *** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
<p>Podemos notar que, mientras los modelos 3 y 4 comparten los mismos estadísticos <span class="math inline">\(R^2\)</span> y el mismo coeficiente para <span class="math inline">\(rooms\)</span>, los coeficientes estimados para <span class="math inline">\(nox\)</span> y <span class="math inline">\(lnox\)</span> sobre <span class="math inline">\(lprice\)</span> son diferentes. Comparemos sus interpretaciones:</p>
<ul>
<li><span class="math inline">\(nox\)</span>: por cada unidad que aumente la concentración de óxido nitroso en el ambiente de la comunidad, el precio mediano de sus casas disminuirá, en promedio, un 12%.</li>
<li><span class="math inline">\(lnox\)</span>: por cada punto porcentual (1%) que aumente la concentración de óxido nitroso en el ambiente de la comunidad, el precio mediano de sus casas disminuirá, en promedio, en un 72%.</li>
</ul>
</div>
</div>
<div id="funciones-cuadráticas" class="section level2">
<h2>3. Funciones cuadráticas</h2>
<p>Se emplean para captar efectos marginales crecientes o decrecientes. En términos matemáticos, se formula</p>
<p><span class="math display">\[
\begin{equation}
y = \beta_0 + \beta_1x + \beta_2x^2
\end{equation}
\]</span>
En R, creamos una nueva variable con el cuadrado de habitaciones <span class="math inline">\(rooms2\)</span>, y luego la incorporamos al modelo como variable explicativa</p>
<pre class="r"><code>hprice2$rooms2 = (hprice2$rooms)^2
m5 = lm(price ~ rooms + rooms2, data = hprice2)
screenreg(list(m5), custom.model.names = c(&quot;Modelo 5&quot;))</code></pre>
<pre><code>## 
## ==========================
##              Modelo 5     
## --------------------------
## (Intercept)   66203.18 ***
##              (12111.41)   
## rooms        -22713.18 ***
##               (3756.83)   
## rooms2         2477.09 ***
##                (290.74)   
## --------------------------
## R^2               0.55    
## Adj. R^2          0.55    
## Num. obs.       506       
## ==========================
## *** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
<p><span class="math display">\[
\begin{equation}
y = \beta_0 + \beta_1x + \beta_2x^2
\end{equation}
\]</span></p>
<p>Dadas las características de una función cuadrática, en este caso no tiene sentido mantener <span class="math inline">\(x^2\)</span> constante mientras varía <span class="math inline">\(x\)</span>, por lo que <span class="math inline">\(\beta_1\)</span> no mide la variación en y respecto de <span class="math inline">\(x\)</span>. Luego, se tiene la aproximación</p>
<p><span class="math display">\[
\begin{equation}
\vartriangle \hat{y} \approx (\beta_1x + 2\beta_2x)\vartriangle x,
\end{equation}
\]</span></p>
<p>de manera que</p>
<p><span class="math display">\[
\begin{equation}
\vartriangle \hat{y} / \vartriangle x \approx \beta_1x + 2\beta_2x
\end{equation}
\]</span></p>
<p>Así, la pendiente de la relación entre <span class="math inline">\(x\)</span> e <span class="math inline">\(y\)</span> depende de <span class="math inline">\(x\)</span>, equivaliendo a <span class="math inline">\(\beta_1x + 2\beta_2x\)</span>. Si <span class="math inline">\(x=0\)</span>, es posible señalar que <span class="math inline">\(\beta_1\)</span> puede interpretarse como la pendiente aproximada al pasar de <span class="math inline">\(x=0\)</span> a <span class="math inline">\(x=1\)</span>. Si queremos conocer el efecto de <span class="math inline">\(x\)</span> sobre <span class="math inline">\(y\)</span>, simplemente interpretamos el coeficiente de la tabla. No obstante, para conocer el efecto de <span class="math inline">\(x\)</span> sobre <span class="math inline">\(y\)</span>, debemos reemplazar para analizar la variabilidad de <span class="math inline">\(y\)</span> por cada unidad que aumenta <span class="math inline">\(x\)</span>. En este caso:</p>
<p><span class="math display">\[
\begin{equation}
price = 66203.18 + -22713.18rooms + 2477.09rooms^2
\end{equation}
\]</span></p>
<p>Así, si queremois conocer la diferencia de precio estimada para una casa de 4 habitaciones versus una de tres:</p>
<ul>
<li><span class="math inline">\(price = 66203.18 + -22713.18*3 + 2477.09*(3)^2 = 66203.18 + -68139.54 + 22293.81 = 20357.45\)</span></li>
<li><span class="math inline">\(price = 66203.18 + -22713.18*4 + 2477.09*(4)^2 = 66203.18 + -90852.72 + 39633.44 = 14983.9\)</span></li>
</ul>
<p>En este caso, el modelo predice que el precio mediano tendería a disminuir en <span class="math inline">\(5373.55\)</span> por cada habitación extra, lo cual sería contraintuitivo. Recordemos que las funciones cuadráticas tienen forma de parábolas, por lo que, pasado un punto máximo o mínimo, la relación se invertirá. Es decir, si para los valores inferiores de <span class="math inline">\(x\)</span> el efecto sobre <span class="math inline">\(y\)</span> es negativo, para los valores superiores el efecto de <span class="math inline">\(x\)</span> sobre <span class="math inline">\(y\)</span> será positivo, y viceversa. Para estimarlo, seguimos la siguiente fórmula:</p>
<p><span class="math display">\[
\begin{equation}
x^* = |{\hat{\beta1}}/(2\hat{\beta_2})|
\end{equation}
\]</span></p>
<p>En nuestro caso, esto equivale a <span class="math inline">\(|{\hat{\beta1}}/(2\hat{\beta_2})| = |-22713.18/2*(2477.09)| = -4.58465\)</span>. Es decir, si <span class="math inline">\(x&gt;-4.58465\)</span>, el efecto será negativo; mientras que valores de <span class="math inline">\(x&lt;-4.58465\)</span> tendrán un efecto positivo sobre <span class="math inline">\(y\)</span>.</p>
</div>
<div id="resumen" class="section level2">
<h2>Resumen</h2>
<p>En este práctico comprendimos cómo las transformaciones funcionales permiten solucionar problemas de estimación al estimar modelos de regresión lineal. Además, aprendimos a analizar los coeficientes de predictores transformados funcionalmente a través de la logaritmización y la elevación al cuadrado.</p>
</div>

                    </div>

                    



                    
                    <div class="article-widget">
                        
<div class="post-nav">
  
  
  
  <div class="post-nav-item">
    <div class="meta-nav">Previous</div>
    <a href="/example/08-practico/" rel="next">Inferencia y predicción</a>
  </div>
  
  
</div>

                    </div>
                    
                </div>

                <div class="body-footer">
                    <p>Last updated on January 1, 0001</p>

                    





                    



                </div>

            </article>

            <footer>
    <hr>

    <div class="row course-info">
        <div class="col-md-7">
            <p>
                <strong>: Estadística II (I° Semestre- 2023)</strong><br>

                <a href="https://www.uahurtado.cl/" target="_blank" rel="noopener">Universidad Alberto Hurtado</a> &emsp;&emsp;
                <a href="https://www.uahurtado.cl/carreras/ciencia-politica/" target="_blank" rel="noopener">Departamento de Ciencia Política y Relaciones Internacionales</a>
            </p>

            <p>
                <a href="https://valentinaandrade.netlify.app/" target="_blank" rel="noopener"><i class="fas fa-user"></i>
                    Valentina Andrade</a> &emsp;&emsp;
                <a href="mailto:valentinaandrade@uchile.cl"><i class="fas fa-envelope"></i>
                    valentinaandrade@uchile.cl</a>
            </p>

            <p>
                <i class="far fa-calendar-alt"></i> Clases: Martes o Jueves (1 bloque) &emsp;&emsp;
                <i class="fas fa-pencil-alt"></i> Práctico: Martes o Jueves (2 bloque) 
                <br><i class="fas fa-university"></i> Sala por definir
            </p>
        </div>

        <div class="col-md-5 credits">
            <p>All content licensed under a <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" rel="noopener">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.</p>
            
            <p>Content <i class="fab fa-creative-commons"></i> 2023. Web developed by Andrew Heiss and custom by <a href="https://valentinaandrade.netlify.app/" target="_blank" rel="noopener">Valentina Andrade</a></p>
        
            <p>This site created with the <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> in <a href="https://bookdown.org/yihui/blogdown/" target="_blank" rel="noopener">blogdown</a> and <a href="https://gohugo.io/" target="_blank" rel="noopener">Hugo</a>. </p>
            
            <p><a href="https://github.com/valentinaandrade" target="_blank" rel="noopener"><i class="fab fa-github"></i> View the source at GitHub.</a></p>
        </div>
    </div>
</footer>


        </main>
    </div>
</div>

        

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/instant.page/5.1.0/instantpage.min.js" integrity="sha512-1+qUtKoh9XZW7j+6LhRMAyOrgSQKenQ4mluTR+cvxXjP1Z54RxZuzstR/H9kgPXQsVB8IW7DMDFUJpzLjvhGSQ==" crossorigin="anonymous"></script>

      
      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      

      
      

      

      

    

    
    
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.2.2/anchor.min.js" integrity="sha512-I7w3ZdSFzw5j3jU3ZkNikBNeIrl3i+hEuEdwNmqUJvwNcaBUNcijnP2gd9DtGlgVYDplfjGoD8vTNsID+lCjqg==" crossorigin="anonymous"></script>
    <script>
      anchors.add();
    </script>
    

    
    
    

    
    

    
    
    
    

    
    <script src="/js/bootstrap.bundle.min.8b7df62fd2da18ce73e29c13cc0a6198.js"></script>

    
    

    
    
    
    
    
    
    
    
    
    <script src="/en/js/wowchemy.min.c6ceb5c48772e46156651a48070d6139.js"></script>

    

<script src="/js/math-code.js"></script>


    
    

    
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>

</html>
