<!DOCTYPE html>
<html lang="en-us" 
      xmlns:og="http://ogp.me/ns#" 
      xmlns:fb="https://www.facebook.com/2008/fbml">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  
  
  
    <meta name="generator" content="Wowchemy 5.2.0 for Hugo" />
  

  

  
  
  
  
  
  

  

  
  
  
    
  
  <meta name="description" content="0. Objetivo del prácticoEl presente práctico tiene dos objetivos:
Comprender conceptualmente el análisis de regresión lineal simple estimado a través de Mínimos Cuadrados Ordinarios (MCO) (o Ordinary Least Squares (OLS) en inglés)." />

  
  <link rel="alternate" hreflang="en-us" href="/example/04-practico/" />

  







  




  
  
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  

  
  
  
    <meta name="theme-color" content="#1a9875" />
  

  
  
    
    <script src="/js/mathjax-config.js"></script>
  

  
  
  
  
    
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha256-FMvZuGapsJLjouA6k7Eo2lusoAX9i0ShlWFG6qt7SLc=" crossorigin="anonymous">

    
    

    
    
    
      
    
    

    
    
    

    

    
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" integrity="" crossorigin="anonymous" async></script>
      
    
      
      

      
      

      
    
      
      

      
      

      
    
  

  
  
  
    
      
      
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Fira+Sans+Condensed:400,400i,700,700i%7CBarlow:ital,wght@0,400;0,700;1,400;1,700&display=swap">
      
    
  

  
  
  
  
  
  <link rel="stylesheet" href="/css/wowchemy.6c40d5e91ad0908cd1753452468e8c67.css" />

  



  

  

  




  
  
  

  

  
    <link rel="manifest" href="/index.webmanifest" />
  

  <link rel="icon" type="image/png" href="/media/icon_hua2ec155b4296a9c9791d015323e16eb5_11927_32x32_fill_lanczos_center_2.png" />
  <link rel="apple-touch-icon" type="image/png" href="/media/icon_hua2ec155b4296a9c9791d015323e16eb5_11927_180x180_fill_lanczos_center_2.png" />

  <link rel="canonical" href="/example/04-practico/" />

  
  
  
  
  
  
  
  
    
    
  
  
  <meta property="twitter:card" content="summary" />
  
    <meta property="twitter:site" content="@valentiandrade" />
    <meta property="twitter:creator" content="@valentiandrade" />
  
  <meta property="og:site_name" content="Estadística II" />
  <meta property="og:url" content="/example/04-practico/" />
  <meta property="og:title" content="Regresión lineal simple | Estadística II" />
  <meta property="og:description" content="0. Objetivo del prácticoEl presente práctico tiene dos objetivos:
Comprender conceptualmente el análisis de regresión lineal simple estimado a través de Mínimos Cuadrados Ordinarios (MCO) (o Ordinary Least Squares (OLS) en inglés)." /><meta property="og:image" content="/media/logo_huec1c53a9c99ba801c510916ffbd8bc18_109138_300x300_fit_lanczos_2.png" />
    <meta property="twitter:image" content="/media/logo_huec1c53a9c99ba801c510916ffbd8bc18_109138_300x300_fit_lanczos_2.png" /><meta property="og:locale" content="en-us" />
  
    
    
  

  



  

  

  <link rel="stylesheet" type="text/css" href="/custom-css/print.css" media="print" />

  <link rel="shortcut icon" href="/favicon.ico" />
  <link rel="apple-touch-icon-precomposed" sizes="57x57" href="/img/apple-touch-icon-57x57.png" />
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/img/apple-touch-icon-114x114.png" />
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/img/apple-touch-icon-72x72.png" />
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/img/apple-touch-icon-144x144.png" />
  <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/img/apple-touch-icon-120x120.png" />
  <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/img/apple-touch-icon-152x152.png" />
  <link rel="icon" type="image/png" href="/img/favicon-32x32.png" sizes="32x32" />
  <link rel="icon" type="image/png" href="/img/favicon-16x16.png" sizes="16x16" />
  <meta name="application-name" content=": Estadística II" />
  <meta name="msapplication-TileColor" content="#FFFFFF" />
  <meta name="msapplication-TileImage" content="/img/mstile-144x144.png" />


  <title>Regresión lineal simple | Estadística II</title>
</head>


<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" class="page-wrapper  ">

  
  
  
  
  
  <script src="/js/wowchemy-init.js"></script>

    




    











  


<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container-xl">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/"><img src="/media/logo_huec1c53a9c99ba801c510916ffbd8bc18_109138_0x70_resize_lanczos_2.png" alt="Estadística II"></a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar-content" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/"><img src="/media/logo_huec1c53a9c99ba801c510916ffbd8bc18_109138_0x70_resize_lanczos_2.png" alt="Estadística II"></a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-end" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"><span>Organización</span><span class="caret"></span>
          </a>
          <div class="dropdown-menu">
            
              <a class="dropdown-item" href="/schedule/"><span>Planificación</span></a>
            
              <a class="dropdown-item" href="/syllabus/"><span>Syllabus</span></a>
            
          </div>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/content/"><span>Clases</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link  active" href="/example/"><span>Prácticos</span></a>
        </li>

        
        

        
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"><span>Evaluaciones <i class="fab fa-github"></i></span><span class="caret"></span>
          </a>
          <div class="dropdown-menu">
            
              <a class="dropdown-item" href="/assignment/"><span>Controles</span></a>
            
              <a class="dropdown-item" href="https://classroom.github.com/classrooms/86887318-learn-r-uah-2021"><span>Github Classroom<i class="fab fa-github"></i></span></a>
            
          </div>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/resource/"><span>Recursos</span></a>
        </li>

        
        

        

        
        
        
          
            
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="https://join.slack.com/t/estadisticaii-uah/shared_invite/zt-1qi7am4o2-7pVVgPC~s0IcBKwqSRWSvQ" target="_blank" rel="noopener"><span><i class="fab fa-slack"></i></span></a>
        </li>

        
        

        

        
        
        
          
            
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="https://rstudio.cloud/" target="_blank" rel="noopener"><span><i class="fab fa-r-project"></i></span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">

      
      

      
      

      
      

      
      

    </ul>

  </div>
</nav>



    

<div class="container-fluid docs">
    <div class="row flex-xl-nowrap">
        <div class="col-12 col-md-3 col-xl-2 docs-sidebar">
            





  
    
  




<form class="docs-search d-flex align-items-center">
  <button class="btn docs-toggle d-md-none p-0 mr-3" type="button" data-toggle="collapse" data-target="#docs-nav" aria-controls="docs-nav" aria-expanded="false" aria-label="Toggle section navigation">
    <span><i class="fas fa-bars"></i></span>
  </button>

  
</form>

<nav class="collapse docs-links" id="docs-nav">
  

  
  
  
    
  

  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/example/">Información general</a>
    <ul class="nav docs-sidenav">
      
      <li >
        <a href="/example/">Prácticos (códigos de ejemplo)</a>
      </li>

      
    </ul>
    

  </div>
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" >Datos</a>

  </div>
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/example/01-practico/">Ejemplos</a>
    <ul class="nav docs-sidenav">
      
      <li >
        <a href="/example/01-practico/">1: Variables aleatorias y distribuciones</a>
      </li>

      
      <li >
        <a href="/example/02-practico/">2: Inferencia</a>
      </li>

      
      <li >
        <a href="/example/032-practico/">3: RMarkdown</a>
      </li>

      
      <li >
        <a href="/example/03-practico/">3: R, RStudio y Github</a>
      </li>

      
      <li class="active">
        <a href="/example/04-practico/">4: Regresión lineal simple</a>
      </li>

      
      <li >
        <a href="/example/05-practico/">5: Regresión lineal simple con diseño muestral y bondad de ajuste</a>
      </li>

      
      <li >
        <a href="/example/06-practico/">6: Regresión lineal múltiple</a>
      </li>

      
      <li >
        <a href="/example/07-practico/">7: Regresión lineal múltiple y predictores categóricos</a>
      </li>

      
      <li >
        <a href="/example/08-practico/">8: Inferencia y predicción</a>
      </li>

      
      <li >
        <a href="/example/09-practico/">9: Transformaciones funcionales</a>
      </li>

      
      <li >
        <a href="/example/10-practico/">10: Relaciones no lineales y términos de interacción</a>
      </li>

      
      <li >
        <a href="/example/11-practico/">11: Chequeo de supuestos</a>
      </li>

      
      <li >
        <a href="/example/12-practico/">12: Errores de medida y procesamiento</a>
      </li>

      
      <li >
        <a href="/example/13-practico/">13: Omisión de variables relevantes</a>
      </li>

      
    </ul>
    

  </div>
  
  
</nav>

        </div>

        
        <div class="d-none d-xl-block col-xl-2 docs-toc">
            <ul class="nav toc-top">
                <li><a href="#" id="back_to_top" class="docs-toc-title">Contents</a></li>
            </ul>

            

 
        </div>
        

        <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 docs-content" role="main">

            <article class="article">

                <div class="docs-article-container">
                    <h1>Regresión lineal simple</h1>

                    

                    

                    

                    <div class="article-style">
                        

<div id="TOC">

</div>

<div id="objetivo-del-práctico" class="section level2">
<h2>0. Objetivo del práctico</h2>
<p>El presente práctico tiene dos objetivos:</p>
<ol style="list-style-type: decimal">
<li><p>Comprender conceptualmente el <strong>análisis de regresión lineal simple</strong> estimado a través de <strong>Mínimos Cuadrados Ordinarios (MCO)</strong> (o <em>Ordinary Least Squares</em> (<em>OLS</em>) en inglés).</p></li>
<li><p>Aprender a estimar una regresión lineal simple en R a través de la función <code>lm()</code>.</p></li>
</ol>
<div id="materiales-de-la-sesión" class="section level3">
<h3>Materiales de la sesión</h3>
<p>En este práctico se utilizarán los datos sobre <strong>salarios</strong> utilizados en el capítulo 2 del libro <em>Introducción a la econometría</em> de J.W. Wooldridge (2015).</p>
<p>Asimismo, la realización de este práctico requiere la carga de diversos <strong>paquetes</strong> que nos permitirán explorar los datos y presentar los modelos estimados.</p>
<pre class="r"><code>if (!require(&quot;pacman&quot;)) install.packages(&quot;pacman&quot;) # Instalamos pacman en caso de necesitarlo
pacman::p_load(wooldridge, #Para descargar los datos
               dplyr, #Para procesar datos
               sjmisc, #Para explorar los datos
               sjPlot, #Para explorar los datos
               texreg) #Para presentar el modelo de regresión estimado</code></pre>
</div>
</div>
<div id="familiarizándose-con-los-datos" class="section level2">
<h2>1. Familiarizándose con los datos</h2>
<p>Como se señalo anteriormente, se trabajará con datos sobre <strong>salarios</strong>. Para cargarlos, utilizamos la función <code>data("wage1")</code></p>
<pre class="r"><code>data(&quot;wage1&quot;)</code></pre>
<p>Nos daremos cuenta de que en nuestro <em>ambiente</em> ha aparecido un dataframe con 526 observaciones y 24 columnas. Particularmente, en este caso trabajaremos con dos variables:</p>
<ul>
<li><strong>wage</strong>: indica el salario por hora en miles de pesos de cada persona en los datos.</li>
<li><strong>educ</strong>: indica el número de años de escolaridad de cada persona en los datos.</li>
</ul>
<p>Las seleccionaremos utilizando la función <code>select()</code> de <code>dplyr</code>, a modo de trabajar con un set de datos más acotado</p>
<pre class="r"><code>wage1 = select(wage1, wage, educ)</code></pre>
<p>Como se ha revisado en las clases, el análisis de regresión busca cuantificar la relación entre dos variables <span class="math inline">\(x\)</span> (independiente, predictora, explicativa, entre otros) e <span class="math inline">\(y\)</span> (dependiente, predicha, explicada, entre otros). En particular, se busca</p>
<ul>
<li>Explicar <span class="math inline">\(y\)</span> en términos de <span class="math inline">\(x\)</span>, o bien</li>
<li>Analizar cómo varía <span class="math inline">\(y\)</span> cuando varía <span class="math inline">\(x\)</span>.</li>
</ul>
<p>En este práctico se busca estimar un modelo de regresión lineal de <strong>wage</strong> (<span class="math inline">\(y\)</span>, variable explicada) sobre <strong>educ</strong> (<span class="math inline">\(x\)</span>, variable explicativa). Antes de adentrarse directamente en la comprensión y estimación de los modelos de regresión lineal simple, es relevante explorar <strong>uni</strong> y <strong>bivariadamente</strong> los datos por analizar. Para ello, nos valdremos de las funciones <code>descr()</code> del paquete <code>sjmisc</code>, que permite describir variables cuantitativas; <code>plot_frq()</code> y <code>plot_scatter</code> de <code>sjPlot</code> para análisis uni y bivariados;y <code>cor()</code> del paquete <code>base</code> de <code>R</code>.</p>
<div id="descriptivos-univariados-con-sjmiscdescr-y-sjplotplot_frq" class="section level3">
<h3>Descriptivos univariados con <code>sjmisc::descr()</code> y <code>sjPlot::plot_frq()</code></h3>
<p>En general, variables de niveles de medición intervalar o de razón (también denominadas genéricamente como variables <strong>cuantitativas</strong>) permiten emplear una serie de propiedades de los números que se traducen en la posibilidad de realizar con ellos operaciones aritméticas como sumar, restar, multiplicar y dividir. Así, es posible estimar para ellas no sólo medidas de posición, sino también otras <strong>medidas de tendencia central</strong> de gran importancia como, en particular, la <strong>media</strong>, así como <strong>medidas de dispersión</strong> tales como la <strong>varianza</strong>. Ambos estadísticos son <strong>fundamentales</strong> en la estimación de modelos de regresión lineal.</p>
<p>En particular, los descriptivos para la variable <strong>wage</strong> se obtienen</p>
<pre class="r"><code>sjmisc::descr(wage1$wage)</code></pre>
<pre><code>## 
## ## Basic descriptive statistics
## 
##  var    type label   n NA.prc mean   sd   se   md trimmed              range
##   dd numeric    dd 526      0  5.9 3.69 0.16 4.65    5.24 24.45 (0.53-24.98)
##   iqr skew
##  3.55 2.01</code></pre>
<p>Siguiendo lo presentado es posible distinguir que, en la muestra, los salarios por hora oscilan entre los .53 y los 24.98 mil pesos chilenos. El <strong>promedio</strong> es de 5.9 mil pesos por hora, mientras que la desviación estándar corresponde a 3.69 mil pesos por hora. Además, la mediana (4.65 mil pesos por hora) es inferior a la media, lo cual indicaría una asimetría positiva en los datos. Considerando una jornada laboral de 44 horas semanales, lo anterior nos indica que, en promedio, los trabajadores de la muestra obtienen un salario mensual promedio de 1038400 pesos.</p>
<p>Un histograma también puede ser útil para identificar la distribución de la variable:</p>
<pre class="r"><code>sjPlot::plot_frq(wage1$wage,
                 title = &quot;Histograma de salarios por hora en miles de pesos&quot;,
                 type = &quot;histogram&quot;)</code></pre>
<p><img src="/example/04-practico_files/figure-html/plot_wage-1.png" width="672" /></p>
<p>En este caso, es posible apreciar que la distribución de la variable presente una <strong>asimetría positiva</strong>, lo cual indica que la mayoría de los datos se concentran en la zona inferior de la distribución (es decir, hay una mayor proporción de salarios por hora bajos en relación con salarios por hora muy altos).</p>
<p>En el caso de los años de escolaridad, la media corresponde a 12.56 años, con una mediana de 4.65 años y una desviación estándar de 3.69. Ello indica que al menos un 50% de las personas en la muestra completaron la enseñanza media.</p>
<pre class="r"><code>descr(wage1$educ)</code></pre>
<pre><code>## 
## ## Basic descriptive statistics
## 
##  var    type label   n NA.prc  mean   sd   se md trimmed     range iqr  skew
##   dd integer    dd 526      0 12.56 2.77 0.12 12   12.69 18 (0-18)   2 -0.62</code></pre>
<p>En lo que respecta a la distribución de la variable <strong>educ</strong>, es posible constatar que la mayoría de los casos se encuentran en torno a la media, que corresponde a 12.56 años de escolaridad, lo cual corresponde a un nivel educacional medio.</p>
<pre class="r"><code>sjPlot::plot_frq(wage1$educ,
                 title = &quot;Histograma de años de escolaridad&quot;,
                 type = &quot;histogram&quot;)</code></pre>
<p><img src="/example/04-practico_files/figure-html/plot_educ-1.png" width="672" /></p>
</div>
<div id="análisis-bivariado-con-basecor-y-sjplotplot_scatter" class="section level3">
<h3>Análisis bivariado con <code>base::cor()</code> y <code>sjPlot::plot_scatter()</code></h3>
<p>Entre otros elementos, algo fundamental que tenemos que considerar a la hora de plantear la estimación de un modelo que busque analizar el efecto de <span class="math inline">\(x\)</span> sobre <span class="math inline">\(y\)</span> es que estas deben estar relacionadas entre sí, al menos de forma moderada. Para estimar la correlación entre dos variables utilizamos <code>base::cor()</code></p>
<pre class="r"><code>cor(wage1$wage, wage1$educ)</code></pre>
<pre><code>## [1] 0.4059033</code></pre>
<p>En este caso la correlación es de 0.41, lo cual corresponde a una relación moderada-fuerte en ciencias sociales. Es posible graficar esta relación con <code>sjPlot::plot_scatter()</code> para analizar con mayor detalle la asociación entre salarios por hora y años de escolaridad</p>
<pre class="r"><code>sjPlot::plot_scatter(wage1, 
                     x = educ, 
                     y = wage,
                     title = &quot;Relación entre salarios (en miles de pesos) por hora y años de escolaridad&quot;,
                     fit.line = &quot;lm&quot;)</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/example/04-practico_files/figure-html/plot_cor-1.png" width="672" /></p>
<p>Si bien no hay claridad de que la relación entre ambas variables sea lineal dada la recta de regresión presentada (lo cual es el supuesto fundamental del análisis de regresión lineal), si se puede identificar una relación positiva entre salarios por hora y años de escolaridad. Ello apoya la hipótesis planteada al inicio del práctico: una mayor escolaridad estará asociada, en promedio, a salarios por hora más elevados.</p>
</div>
</div>
<div id="estimando-un-modelo-de-regresión-lineal-simple-con-lm" class="section level2">
<h2>2. Estimando un modelo de regresión lineal simple con <code>lm()</code></h2>
<p>En general, la estimación de modelos de regresión lineal simple en R es sencilla en términos de código. Antes de ello, sin embargo, consideremos la formalización del modelo de regresión lineal por estimar</p>
<p><span class="math display">\[
\begin{equation}
\hat{wage} = \beta_0 + \beta_1educ_{i} + u_{i}
\end{equation}
\]</span>
Es decir: el salario por hora predicho corresponde a la suma del <strong>intercepto de regresión</strong> <span class="math inline">\(\beta_0\)</span>, más el valor estimado para el coeficiente de regresión <span class="math inline">\(\beta_1\)</span> estimado para la variable <strong>educ</strong> por el valor observado en esa variable para cada sujeto, más el error <span class="math inline">\(u_{i}\)</span> asociado a cada observación. En términos generales:</p>
<ul>
<li><p><span class="math inline">\(\beta_0\)</span>: Corresponde al valor estimado para <span class="math inline">\(\hat{y}\)</span> para alguien con cero años de escolaridad.</p></li>
<li><p><span class="math inline">\(\beta_1\)</span>: Corresponde a la <strong>pendiente</strong> estimada para la función de regresión lineal de <span class="math inline">\(\hat{y}\)</span> sobre <span class="math inline">\(x\)</span>. Así, por cada unidad que aumente <span class="math inline">\(x\)</span> (en este caso, por cada año de escolaridad extra), el valor estimado <span class="math inline">\(\hat{y}\)</span> para los salarios por hora aumentará o disminuirá en <span class="math inline">\(\beta_1\)</span>.</p></li>
<li><p><span class="math inline">\(u_{i}\)</span>: Corresponde al error en la estimación, generado por la no incorporación en el modelo de variables que estén relacionadas con <strong>wage</strong>. En este caso, incluir variables como el área de actividad económica, la ocupación, la capacidad de liderazgo o resolución de problemas, entre otros, puede disminuir el error causado por la no observación de efectos estadísticamente significativos de estas variables sobre los salarios por hora.</p></li>
</ul>
<p>Sin embargo, para simplificar el análisis, en el práctico sólo nos enfocaremos en <span class="math inline">\(\beta_0\)</span> y <span class="math inline">\(\beta_1\)</span>. Para estimar un modelo de regresión simple, debe utilizarse el siguiente código</p>
<pre class="r"><code>mod = lm(wage ~ educ, data = wage1)</code></pre>
<p>En términos sencillos, el anterior código indica a R que</p>
<ul>
<li>Cree un nuevo objeto llamado <strong>mod</strong> (recordemos que <code>=</code> indica <strong>asignación</strong>);</li>
<li>Este nuevo objeto será un modelo de regresión lineal estimado con <code>lm()</code>,</li>
<li>En el cual la variable explicada <span class="math inline">\(y\)</span> corresponde a <strong>wage</strong> (lo que antecede a <code>~</code>),</li>
<li>Mientras que la variable explicativa <span class="math inline">\(x\)</span> corresponde a <strong>educ</strong> (lo que sucede a <code>~</code>),</li>
<li>Utilizando los datos del objeto <code>wage1</code>.</li>
<li>Es decir: lm(<span class="math inline">\(y\)</span> ~ <span class="math inline">\(x_1\)</span>, datos).</li>
</ul>
<p>Luego de ejecutar ese código, se generará en el <em>ambiente</em> un objeto llamado <strong>mod</strong>, que corresponde a una lista con 12 elementos. No nos adentraremos en ello en esta clase, pues el foco está en la estimación y comprensión estadística de los modelos de regresión lineal simple.</p>
</div>
<div id="comprendiendo-el-output-de-lm" class="section level2">
<h2>3. Comprendiendo el output de <code>lm()</code></h2>
<p>Luego de haber creado el objeto que contiene el modelo de regresión lineal simple estimado, debemos proceder a presentarlo para poder analizar los resultados. Para ello utilizaremos la función <code>screenreg()</code> de <code>texreg</code>.</p>
<pre class="r"><code>screenreg(mod)</code></pre>
<pre><code>## 
## =======================
##              Model 1   
## -----------------------
## (Intercept)   -0.90    
##               (0.68)   
## educ           0.54 ***
##               (0.05)   
## -----------------------
## R^2            0.16    
## Adj. R^2       0.16    
## Num. obs.    526       
## =======================
## *** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
<p>En la tabla se presentan diversos estadísticos. Revisemos los resultados con mayor atención, fila por fila:</p>
<ul>
<li><p><strong>Model 1</strong>: Indica el modelo presentado. Esto es útil en casos donde presentamos más de un modelo.</p></li>
<li><p><strong>(Intercept)</strong>: Indica el valor estimado para el intercepto de regresión o <span class="math inline">\(\beta_0\)</span>. Ello indica que, cuando <span class="math inline">\(educ_i = 0\)</span>, el salario por hora predicho corresponde a <strong>-.9</strong> mil pesos. El valor en paréntesis que le sigue corresponde al <strong>error estándar</strong> estimado para el intercepto.</p></li>
<li><p><strong>educ</strong>: Corresponde al coeficiente de regresión estimado para la variable explicativa <strong>educ</strong>, o <span class="math inline">\(\beta_1\)</span>. De ese modo el modelo estima que, por cada año de escolaridad que se aumente, el salario por hora predicho aumentará en <strong>.54</strong> mil pesos. El valor en paréntesis que le sigue corresponde al <strong>error estándar</strong> estimado para el coeficiente.</p></li>
<li><p><strong>R^2</strong> y <strong>Adj. R^2</strong>: Corresponden a las medidas de ajuste del modelo. Esto se revisará con detención en el <strong>práctico 5</strong>.</p></li>
<li><p><strong>Num. obs</strong>: Número de observaciones con las cuales se estimó el modelo. En este caso, se utilizó la totalidad de la muestra, que cuenta con 526 casos. Es fundamental considerar que la estimación de modelos de regresión lineal sólo utiliza observaciones que cuenten con casos válidos en <span class="math inline">\(x\)</span> <strong>y</strong> en <span class="math inline">\(y\)</span>, por lo cual el trabajo de <strong>procesamiento de datos</strong> es fundamental para lograr un buen análisis.</p></li>
<li><p><strong>*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</strong>: Indican el p-valor estimado para cada coeficiente. Esto se abordará con profundidad en el <strong>práctico 8</strong>.</p></li>
</ul>
<p>Así, siguiendo la formalización planteada anteriormente y los resultados obtenidos, es posible plantear que</p>
<p><span class="math display">\[
\begin{equation}
\hat{wage} = -.9 + .54 educ_{i}
\end{equation}
\]</span></p>
</div>
<div id="interpretando-un-modelo-de-regresión-lineal-simple" class="section level2">
<h2>4. Interpretando un modelo de regresión lineal simple</h2>
<p>Ahora sólo nos falta <strong>interpretar</strong> el modelo estimado. Para ello hay que tomar en cuenta los valores estimados para <span class="math inline">\(\beta_0\)</span> y <span class="math inline">\(\beta_1\)</span></p>
<ul>
<li><p><span class="math inline">\(\beta_0\)</span>: Como se señaló anteriormente, el intercepto corresponde al valor predicho <span class="math inline">\(\hat{y}\)</span> cuando <span class="math inline">\(x_1 = 0\)</span>. En este caso, indica el salario por hora predicho en promedio para personas con 0 años de escolaridad.</p></li>
<li><p><span class="math inline">\(\beta_1\)</span>: en este caso, el valor positivo del coeficiente (<span class="math inline">\(\beta_1 &gt; 0\)</span>) indica que existe un <strong>efecto positivo</strong> de los años de escolaridad sobre el salario por hora predicho: mientras más años de escolaridad se tengan, más alto debiese ser el salario por hora percibido. En términos concretos: se espera que, en promedio, una persona con 11 años de escolaridad perciba un salario por hora <strong>.54</strong> mil pesos más alto que alguien con 10 años de escolaridad. Es posible estimar los valores predichos para corroborarlo:</p></li>
</ul>
<p><span class="math display">\[
\begin{equation}
\hat{wage_1} = -.9 + .54 educ_{i} = -.9 + .54*10 = 4.5
\end{equation}
\]</span>
<span class="math display">\[
\begin{equation}
\hat{wage_2} = -.9 + .54 educ_{i} = -.9 + .54*11 = 5.04
\end{equation}
\]</span>
Luego, <span class="math inline">\(5.04-4.5 = .54 = \beta_1\)</span>.</p>
<p>De lo anterior se sigue que</p>
<ul>
<li>Se espera que <span class="math inline">\(\beta_1 \neq 0\)</span> pues, de lo contrario, no existiría un efecto estadísticamente significativo de <span class="math inline">\(x_1\)</span> sobre <span class="math inline">\(y\)</span>.</li>
<li>Asimismo, mientras mayor sea <span class="math inline">\(|\beta_1|\)</span>, mayor será la magnitud del efecto de <span class="math inline">\(x_1\)</span> sobre <span class="math inline">\(y\)</span> y viceversa.</li>
<li>Si <span class="math inline">\(\beta_1 &gt; 0\)</span>, el efecto de <span class="math inline">\(x_1\)</span> sobre <span class="math inline">\(y\)</span> es <strong>positivo</strong>.</li>
<li>Si <span class="math inline">\(\beta_1 &lt; 0\)</span>, el efecto de <span class="math inline">\(x_1\)</span> sobre <span class="math inline">\(y\)</span> es <strong>negativo</strong>.</li>
</ul>
</div>
<div id="cómo-se-estima-beta_1" class="section level2">
<h2>5. ¿Cómo se estima <span class="math inline">\(\beta_{1}\)</span>?</h2>
<p>Como es posible constatar, la estimación de modelos de regresión lineal simple en R es bastante sencilla en términos de código: lo más relevante es indicar claramente cuál es la variable <span class="math inline">\(x\)</span>, y cuál es la variable <span class="math inline">\(y\)</span>. Sin embargo, es importante comprender conceptual y matemáticamente cómo se estima <span class="math inline">\(\beta_1\)</span>.</p>
<p>Como se señaló al inicio del práctico, el método de estimación de <strong>Mínimos Cuadrados Ordinarios (MCO)</strong> (u <em>OLS</em> en inglés). Ello indica que la estimación busca optimizar una recta que se ajuste a los datos disminuyendo al máximo la suma de los <strong>residuos</strong> al cuadrado. Los residuos se elevan al cuadrado para sumarlos, lo cual se denomina <strong>Suma de residuos al cuadrado</strong> o <span class="math inline">\(SS_{residual}\)</span>. Esto para evitar que residuos positivos y negativos se anulen entre sí.</p>
<p>Ahora ¿qué son los residuos? Estos corresponden a la <strong>diferencia</strong> entre el valor <strong>predicho</strong> y el valor <strong>observado</strong>. Si, por ejemplo, el salario por horas predicho corresponde a 4 mil pesos, y el valor observado corresponde a 3.7 mil pesos por hora, entonces el residuo de la estimación para esta observación equivale a -.3 mil pesos.</p>
<p>Considérese la ecuación</p>
<p><span class="math display">\[
\begin{equation}
\hat{y} = \beta_0 + \beta_1x_{i}
\end{equation}
\]</span>
, donde</p>
<ul>
<li><span class="math inline">\(\beta_0 = \hat{y} - \beta_1\)</span>;</li>
<li><span class="math inline">\(\beta_1 = \frac{Cov(XY)}{VarX}\)</span>, donde
<ul>
<li><span class="math inline">\(Cov(XY) = \frac{\sum_{i=1}^{n}(x_i - \bar{x})(y_i - \bar{y})}{n-1}\)</span>, y</li>
<li><span class="math inline">\(VarX = \frac{\sum_{i=1}^{n}(x_i - \bar{x})(x_i - \bar{x})}{n-1}\)</span></li>
</ul></li>
</ul>
<p>Luego, es posible simplificar de la siguiente manera</p>
<p><span class="math display">\[
\begin{equation}
\beta_1 = \frac{\sum_{i=1}^{n}(x_i - \bar{x})(y_i - \bar{y})}{\sum_{i=1}^{n}(x_i - \bar{x})(x_i - \bar{x})} = \frac{\sum_{i=1}^{n}(y_i - \bar{y})}{\sum_{i=1}^{n}(x_i - \bar{x})}
\end{equation}
\]</span></p>
<p>A continuación, crearemos variables que reflejen la diferencia entre los valores observados <span class="math inline">\(x_i\)</span> e <span class="math inline">\(y_i\)</span> y el promedio <span class="math inline">\(\bar{x}\)</span> y <span class="math inline">\(\bar{y}\)</span>, respectivamente:</p>
<pre class="r"><code>wage1$difx = wage1$educ-mean(wage1$educ)
wage1$dify = wage1$wage-mean(wage1$wage)</code></pre>
<p>Con ello procedemos a calcular la diferencia de productos cruzados <span class="math inline">\((x_i - \bar{x})(y_i - \bar{y})\)</span>, y la diferencia de cada valor observado de <span class="math inline">\(x\)</span> con su promedio al cuadrado <span class="math inline">\((x_i - \bar{x})^2\)</span></p>
<pre class="r"><code>wage1$difcru = wage1$difx*wage1$dify
wage1$difx2 = wage1$difx^2
head(wage1)</code></pre>
<pre><code>##   wage educ       difx       dify     difcru      difx2
## 1 3.10   11 -1.5627376 -2.7961028  4.3695751  2.4421489
## 2 3.24   12 -0.5627376 -2.6561027  1.4946890  0.3166737
## 3 3.00   11 -1.5627376 -2.8961027  4.5258487  2.4421489
## 4 6.00    8 -4.5627376  0.1038973 -0.4740562 20.8185748
## 5 5.30   12 -0.5627376 -0.5961025  0.3354493  0.3166737
## 6 8.75   16  3.4372624  2.8538973  9.8095938 11.8147725</code></pre>
<p>Así, es posible obtener la suma de productos cruzados <span class="math inline">\((x_i - \bar{x})(y_i - \bar{y})\)</span>, y la suma de cuadrados de X <span class="math inline">\((x_i - \bar{x})^2\)</span></p>
<pre class="r"><code>sum(wage1$difcru)</code></pre>
<pre><code>## [1] 2179.204</code></pre>
<pre class="r"><code>sum(wage1$difx2)</code></pre>
<pre><code>## [1] 4025.43</code></pre>
<p>Reemplazamos los valores en la fórmula anterior:</p>
<p><span class="math display">\[
\begin{equation}
\beta_1 = \frac{\sum_{i=1}^{n}(x_i - \bar{x})(y_i - \bar{y})}{\sum_{i=1}^{n}(x_i - \bar{x})(x_i - \bar{x})} = \frac{2179.204}{4025.43} = 0.54
\end{equation}
\]</span></p>
<p>Y estimamos el intercepto reemplazando por valores ficticios</p>
<p><span class="math display">\[
\begin{equation}
\beta_0 = \hat{y} - \beta_1x_i = 6.12-(.54*13) = 6.12*7.02 = -.9
\end{equation}
\]</span>
Así, la ecuación estimada manualmente es idéntica a la estimada a través de <code>lm()</code></p>
<p><span class="math display">\[
\begin{equation}
\hat{y} = -.9 + .54 x_{i}
\end{equation}
\]</span></p>
<div id="desafío-estimando-beta_1" class="section level3">
<h3><strong>Desafío</strong>: estimando <span class="math inline">\(\beta_{1}\)</span></h3>
<p>¡Ahora es su turno! Utilizando la tabla presentada a continuación, deben estimar manualmente el valor de <span class="math inline">\(\beta_1\)</span>, siguiendo los pasos detallados recientemente</p>
<pre class="r"><code>print(head(wage1[,1:2], 10))</code></pre>
<pre><code>##     wage educ
## 1   3.10   11
## 2   3.24   12
## 3   3.00   11
## 4   6.00    8
## 5   5.30   12
## 6   8.75   16
## 7  11.25   18
## 8   5.00   12
## 9   3.60   12
## 10 18.18   17</code></pre>
<p>La correcta realización del desafío significará una bonificación individual de <strong>.5 décimas</strong> en la nota obtenida en la prueba del curso ¡mucha suerte!</p>
</div>
</div>
<div id="resumen" class="section level2">
<h2>Resumen</h2>
<p>En este práctico comprendimos conceptualmente los modelos de regresión lineal simple, con especial atención en los conceptos de intercepto y pendiente. También aprendimos a estimar este tipo de modelos con <code>lm()</code></p>
</div>

                    </div>

                    



                    
                    <div class="article-widget">
                        
<div class="post-nav">
  
  
  
  <div class="post-nav-item">
    <div class="meta-nav">Previous</div>
    <a href="/example/13-practico/" rel="next">Omisión de variables relevantes</a>
  </div>
  
  
  
  <div class="post-nav-item">
    <div class="meta-nav">Next</div>
    <a href="/example/05-practico/" rel="prev">Regresión lineal simple con diseño muestral y bondad de ajuste</a>
  </div>
  
</div>

                    </div>
                    
                </div>

                <div class="body-footer">
                    <p>Last updated on January 1, 0001</p>

                    





                    



                </div>

            </article>

            <footer>
    <hr>

    <div class="row course-info">
        <div class="col-md-7">
            <p>
                <strong>: Estadística II (I° Semestre- 2023)</strong><br>

                <a href="https://www.uahurtado.cl/" target="_blank" rel="noopener">Universidad Alberto Hurtado</a> &emsp;&emsp;
                <a href="https://www.uahurtado.cl/carreras/ciencia-politica/" target="_blank" rel="noopener">Departamento de Ciencia Política y Relaciones Internacionales</a>
            </p>

            <p>
                <a href="https://valentinaandrade.netlify.app/" target="_blank" rel="noopener"><i class="fas fa-user"></i>
                    Valentina Andrade</a> &emsp;&emsp;
                <a href="mailto:valentinaandrade@uchile.cl"><i class="fas fa-envelope"></i>
                    valentinaandrade@uchile.cl</a>
            </p>

            <p>
                <i class="far fa-calendar-alt"></i> Clases: Martes o Jueves (1 bloque) &emsp;&emsp;
                <i class="fas fa-pencil-alt"></i> Práctico: Martes o Jueves (2 bloque) 
                <br><i class="fas fa-university"></i> Sala por definir
            </p>
        </div>

        <div class="col-md-5 credits">
            <p>All content licensed under a <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" rel="noopener">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.</p>
            
            <p>Content <i class="fab fa-creative-commons"></i> 2023. Web developed by Andrew Heiss and custom by <a href="https://valentinaandrade.netlify.app/" target="_blank" rel="noopener">Valentina Andrade</a></p>
        
            <p>This site created with the <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> in <a href="https://bookdown.org/yihui/blogdown/" target="_blank" rel="noopener">blogdown</a> and <a href="https://gohugo.io/" target="_blank" rel="noopener">Hugo</a>. </p>
            
            <p><a href="https://github.com/valentinaandrade" target="_blank" rel="noopener"><i class="fab fa-github"></i> View the source at GitHub.</a></p>
        </div>
    </div>
</footer>


        </main>
    </div>
</div>

        

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/instant.page/5.1.0/instantpage.min.js" integrity="sha512-1+qUtKoh9XZW7j+6LhRMAyOrgSQKenQ4mluTR+cvxXjP1Z54RxZuzstR/H9kgPXQsVB8IW7DMDFUJpzLjvhGSQ==" crossorigin="anonymous"></script>

      
      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      

      
      

      

      

    

    
    
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.2.2/anchor.min.js" integrity="sha512-I7w3ZdSFzw5j3jU3ZkNikBNeIrl3i+hEuEdwNmqUJvwNcaBUNcijnP2gd9DtGlgVYDplfjGoD8vTNsID+lCjqg==" crossorigin="anonymous"></script>
    <script>
      anchors.add();
    </script>
    

    
    
    

    
    

    
    
    
    

    
    <script src="/js/bootstrap.bundle.min.8b7df62fd2da18ce73e29c13cc0a6198.js"></script>

    
    

    
    
    
    
    
    
    
    
    
    <script src="/en/js/wowchemy.min.c6ceb5c48772e46156651a48070d6139.js"></script>

    

<script src="/js/math-code.js"></script>


    
    

    
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>

</html>
